### ISSUE TITLE
Add some icons for programming language types

### ISSUE THREAD

**Issue by stardiviner** [domtronn/all-the-icons.el#102]
As in this discussion thread https://github.com/company-mode/company-mode/issues/208 . 
I hope `all-the-icons` can have some icons for programming language types.

**Comment by wyuenho** [comment]
Meh, on IDEs, they are usually just denoted with some circles or triangles, I'm not sure they have that much value. But if you really want to do it, you should be able to hack up a company frontend to do this easily.
