### ISSUE TITLE
feature request: iconify an org buffer, and/or agenda buffer.

### ISSUE THREAD

**Issue by timoc** [domtronn/all-the-icons.el#103]
It would be great if i could overlay an icon on top of a TODO keyword in an org buffer.
Ideally it could replace the TODO keyword and the single '*' if
#+STARTUP: hidestars 
is set.

**Comment by stardiviner** [comment]
You can check out `org-bullets`, Might can use some tricky in `org-bullets`.

**Comment by stardiviner** [comment]
Like this

![image](https://user-images.githubusercontent.com/378699/35978114-cb0dfb6a-0d1f-11e8-945d-b8e407523d60.png)

**Comment by timoc** [comment]
Thanks , but I'm not looking at changing the outline icons, rather i am looking to change the TODO keywords into icons.

**Comment by stardiviner** [comment]
It is possible too! Let me take a try.

**Comment by stardiviner** [comment]
Seems impossible for now. Unless you ask org-mode to change how those keywords insertation.

**Comment by stardiviner** [comment]
Or you need to regexp match to overlay replace. That's possible.

**Comment by JSDurand** [comment]
@stardiviner Might I ask how did you achieve the effect in the screenshot? I am struggling to use all-the-icons in org bullets. They show up correctly if I insert the icons, or in dired buffers, but they show some strange characters if used in org bullets, as in the picture.
![Uploading Capture d’écran 2019-02-15 à 21.39.32.png…]()
