### ISSUE TITLE
[Question] Why all-the-icons-icon-for-mode create idle timers?

### ISSUE THREAD

**Issue by stardiviner** [domtronn/all-the-icons.el#113]
I have following config:
```elisp
(defun *major-mode ()
  "The major mode, including process, environment and text-scale info."
  (if (cdr (assoc major-mode all-the-icons-mode-icon-alist))
      ;; (all-the-icons-icon-for-buffer)
      ;; (all-the-icons-auto-mode-match?)
      (all-the-icons-icon-for-mode major-mode :v-adjust -0.1 :height 1.0)
    ;; (all-the-icons-icon-for-file (buffer-file-name) :v-adjust -0.05 :height 1.0)
    (propertize (format-mode-line "%m" mode-name)
                'face 'mode-line-data-face)
    ))
```

And I execute `helm-timers` found there are some timers are from all-the-icons.

![all-the-icons major-mode timers](https://user-images.githubusercontent.com/378699/39669419-bfc9f79e-511d-11e8-844a-45615722bcb4.png)

My question is why need to create those timers? After did some profiling with Emacs `profiler`. Found it might slow down performance a little. Is it really necessary?

**Comment by stardiviner** [comment]
I found why now, it is because `memoize` is used. `(memoize 'all-the-icons-icon-for-mode)`.
Is this `memoize` must necessary?

**Comment by wyuenho** [comment]
Judging from memoize's source, looks it's there to implement some sort of poor-man's weakref. It basically runs the timer every 2 hours by default to free up memory. I would imagine this was put in place to speed up icon look ups from that flat list. Lots of linear searches are expensive.

**Comment by harizvi** [comment]
I just hit this issue, with my timers list showing 680 outstanding timers. I had visited a few large directories with dired!   The reason I started looking was because Emacs was running "laggy", esp with ivy-switch-buffer acting weirdly. Just wondering if this is not considered a problem?

**Comment by mpereira** [comment]
Another one bumping into this. My Emacs currently has **2000** non-idle timers started by all-the-icons.

Would keeping an in-memory hash map cache of icons be sufficient as a performance-improving alternative?

**Comment by wyuenho** [comment]
> Would keeping an in-memory hash map cache of icons be sufficient as a performance-improving alternative?

Perhaps. Care to submit a PR to replace memoize?

**Comment by yantar92** [comment]
> Perhaps. Care to submit a PR to replace memoize?

As a simple solution, `all-the-icons` can set `memoize-default-timeout` to `nil` when defining memoized functions. The timers will not be created then. This should not cause any significant memory leaks since the number of possible function arguments is finite (and relatively small).

**Comment by mpereira** [comment]
@wyuenho I unfortunately don't have a lot of free time these days. Does it make sense to re-open this ticket for visibility?
