### ISSUE TITLE
Some fonts don't show up correctly(windows)

### ISSUE THREAD

**Issue by TerminatorP** [domtronn/all-the-icons.el#114]
I have correctly installed the fonts provided in this repository in my windows machine. The file icons font and material design show up as expected, however, the fonts for weather icons, octicons, and font awesome icons don't show up even though they are installed in my system.

**Comment by seagle0128** [comment]
Similar issues for me. Some fonts/icons don't show correctly, on Ubuntu 18.04 and macOS. Although the same font, showed different icons on different OS. Wired...

**Comment by TerminatorP** [comment]
I am using vim now.

**Comment by wyuenho** [comment]
Should be fixed by #106. Closing this. Please reopen if master doesn't fix your issue.
