### ISSUE TITLE
Icons change to a different font when changing face properties

### ISSUE THREAD

**Issue by nukeop** [domtronn/all-the-icons.el#115]
Suppose I have a `(all-the-icons-icon-for-mode 'python-mode)`, which shows up as expected. I want to change its color and put it in my modeline, so I do `(propertize (format " %s " all-the-icons-icon-for-mode 'python-mode)) face '(:foreground "#FFFFFF"))`. Now the icon changes to doxygen, which has the same hex value as python's icon, except it's in incorrect font. Why does that happen?

**Comment by seagle0128** [comment]
Same issue here. So buggy...

**Comment by wyuenho** [comment]
Which Emacs port are you using?

**Comment by seagle0128** [comment]
I am using GNU Emacs.

**Comment by wyuenho** [comment]
I mean which GUI port

**Comment by seagle0128** [comment]
GNU Emacs 26.1 on Windows 10

**Comment by wyuenho** [comment]
Try this:

1. M-x describe-fontset
2. Pick fontset-default
3. isearch for `#xE000`

There should be a couple of other fonts listed in that block, can you paste the order of those fonts here?

**Comment by nukeop** [comment]
I'm using GNU Emacs on Linux.
Here's the result for #xE000:
` ..  (#xE000 .. #xF8FF)`

The left one looks like the old Mozilla logo and the one on the right is the Apple logo.

**Comment by nukeop** [comment]
I can see this:
`[-unknown-all-the-icons-normal-normal-normal-*-19-*-*-*-*-0-iso10646-1]`

and some other regular fonts

**Comment by wyuenho** [comment]
Then the problem you've described should no longer happen right? The reason you saw the doxygen icon was because Emacs fell back to file icons, but if you don't even see it on your fontset, you shouldn't see any file icons at all. Have you updated you updated your font cache?

**Comment by nukeop** [comment]
Apparently - yeah, I couldn't find an example of a broken symbol anymore, I'm not sure when that got fixed or why. I'm pretty sure though that it still occurs on my Thinkpad, I'll check back later.

**Comment by seagle0128** [comment]
I got the list.
```elisp
 ..  (#xE000 .. #xF6D8)
    -outline-微软雅黑-normal-normal-normal-sans-*-150-*-*-p-*-iso10646-1
 ..  (#xF6D9 .. #xF6DB)
    -outline-Consolas-normal-normal-normal-mono-*-125-*-*-c-*-iso10646-1
 ..  (#xF6DC .. #xF8E4)
    -outline-微软雅黑-normal-normal-normal-sans-*-150-*-*-p-*-iso10646-1
 ..  (#xF8E5 .. #xF8FE)
    -outline-Consolas-normal-normal-normal-mono-*-125-*-*-c-*-iso10646-1
 .. ﹏ (#xF8FF .. #xFE4F)
    -outline-微软雅黑-normal-normal-normal-sans-*-150-*-*-p-*-iso10646-1
﹐ .. ﹯ (#xFE50 .. #xFE6F)
    -outline-Consolas-normal-normal-normal-mono-*-125-*-*-c-*-iso10646-1
ﹰ .. 𖿟 (#xFE70 .. #x16FDF)
    -outline-微软雅黑-normal-normal-normal-sans-*-150-*-*-p-*-iso10646-1
𖿠 .. 𖿿 (#x16FE0 .. #x16FFF)
    -outline-Consolas-normal-normal-normal-mono-*-125-*-*-c-*-iso10646-1
𗀀 .. 🃿 (#x17000 .. #x1F0FF)
    -outline-微软雅黑-normal-normal-normal-sans-*-150-*-*-p-*-iso10646-1
🄀 .. 🇿 (#x1F100 .. #x1F1FF)
    -outline-Consolas-normal-normal-normal-mono-*-125-*-*-c-*-iso10646-1
🈀 .. 🋿 (#x1F200 .. #x1F2FF)
    -outline-微软雅黑-normal-normal-normal-sans-*-150-*-*-p-*-iso10646-1
🌀 .. 🧿 (#x1F300 .. #x1F9FF)
    -outline-Consolas-normal-normal-normal-mono-*-125-*-*-c-*-iso10646-1
🨀 .. 􏿿 (#x1FA00 .. #x10FFFF)
    -outline-微软雅黑-normal-normal-normal-sans-*-150-*-*-p-*-iso10646-1
  ..   (#x110000 .. #x17FFFF)
... (too long...)
```

**Comment by wyuenho** [comment]
Looks like you need to install the fonts

**Comment by seagle0128** [comment]
Which fonts? I've already installed all fonts from `all-the-icons`.

![image](https://user-images.githubusercontent.com/140797/41654802-2eef5c82-74bd-11e8-8824-2b017b8ee424.png)

**Comment by wyuenho** [comment]
But apparently Emacs hasn't picked up the fonts, at least not in the fontset you showed me. Check your other fontsets in Emacs, if you don't see the icon fonts in either the default fontset or auto*, you'll have to find out if there's anything changing your fontsets or you need to update the font cache in Windows or something.

**Comment by wyuenho** [comment]
Also see #106

**Comment by seagle0128** [comment]
I found some clues. If I enable Chinese fonts in Emacs, the issue appears.

**Comment by seagle0128** [comment]
I figured out the root cause and fixed it. Try this (or add/remove the charsets):

```elisp
      (dolist (charset '(kana han cjk-misc bopomofo gb18030))
        (set-fontset-font "fontset-default" charset "github-octicons" nil 'append)
        (set-fontset-font "fontset-default" charset "FontAwesome" nil 'append)
        (set-fontset-font "fontset-default" charset "Material Icons" nil 'append))))
```

**Comment by nukeop** [comment]
In my case, fileicons are correct, but other icon sets, such as octicons, are broken. Icons for some modes are still broken too, for example the RJSX mode one. In some cases, the icons also change line height.

**Comment by nukeop** [comment]
Another weird quirk: I can use `(all-the-icons-faicon "symbol")` to load an icon to display in the mode line and it shows up correctly, but after opening a buffer that uses a different icon font, the symbol changes to something else.
