### ISSUE TITLE
No icon for .rst extension

### ISSUE THREAD

**Issue by valignatev** [domtronn/all-the-icons.el#116]
UPD check https://github.com/domtronn/all-the-icons.el/issues/116#issuecomment-398727515

What do you think about using book icon for `.rst` files? `.rst` is ReStructuredText, similar to markdown.

Old issue text goes next:
Hi, thanks for a great package!
I noticed that `README.rst` and `other-file-name.rst` have a different file icon:
![image](https://user-images.githubusercontent.com/7038954/41496093-50d4069a-717a-11e8-8f00-8b1dfdb60028.png)

Is this intended? If it's a bug, maybe I can configure it with some workaround? I'll appreciate any tip.

P.S. I'm aware of #105, so I have font-lock+ installed, and for the most part icons are working great.

**Comment by wyuenho** [comment]
Have you seen #106?

**Comment by valignatev** [comment]
@wyuenho It's probably not related. PR makes icons work without need to use font-lock+ wihch I'm using, so PR shouldn't affect me. I think it becasue icon being choosed based on filename here instead of an extension. Check this: https://github.com/domtronn/all-the-icons.el/blob/52d1f2d36468146c93aaf11399f581401a233306/all-the-icons.el#L141

Now, when I jumped into code, I see that `.rst` just doesn't have its own icon. Probably I should rename the issue

**Comment by wyuenho** [comment]
Then is isn't really a bug right? README is special-cased.

**Comment by valignatev** [comment]
Yeah, now I understand it. Updated the issue text.

**Comment by wyuenho** [comment]
ReStructuredText is one of the few OSS project that doesn't have its own logo, so the next best thing is a generic document icon, which is appropriate given its intended usage. Special-casing README also makes sense.
