### ISSUE TITLE
Wrong icons being loaded.

### ISSUE THREAD

**Issue by RJTK** [domtronn/all-the-icons.el#121]
I've installed via `(use-package all-the-icons :ensure t)` and then downloaded the icons with `all-the-icons-install-fonts`.  However, it seems that the wrong icons are being loaded:

![all-the-icons-mixed-up](https://user-images.githubusercontent.com/6856593/45259020-f7da4080-b388-11e8-91b3-3e719a0a9e4a.jpg)

I've tried reinstalling and restarting emacs.

I'm on GNU Emacs 25.3.2, and Linux Mint 17

**Comment by terlar** [comment]
I can verify that using this branch https://github.com/ubolonton/all-the-icons.el/tree/font-lock-fix fixes the issue for me. Give it a go.

**Comment by ogonki-vetochki** [comment]
on MacOS Mojave it worked for me to manually download `.ttf` files to `/System/Library/Fonts` instead of '~/Library/Fonts` as suggested by `all-the-icons-font-install`

**Comment by wyuenho** [comment]
Fixed by #106
