### ISSUE TITLE
Mode line graphical glitch after shrinking minibuffer

### ISSUE THREAD

**Issue by ChoppinBlockParty** [domtronn/all-the-icons.el#125]
I have originally opened [an issue](https://github.com/abo-abo/swiper/issues/1785) in Ivy project. After some discussions and a lot of testing I had found that it is related to all-the-icons in my mode line, any suggestions are appreciated.

**Comment by wyuenho** [comment]
Emacs on X has always had redrawing issues until very recently. Either try compiling from master or report this upstream.
