### ISSUE TITLE
Bug if given a direcotry with "/" at the end and the directory is not git repository

### ISSUE THREAD

**Issue by palikar** [domtronn/all-the-icons.el#127]
Hi.

OK, this is a weird issue and I found it because it causes problems with Neotree [(here)](https://github.com/jaypei/emacs-neotree/issues/307). So, if I want to get the icon of a directory that is a git repository everything works fine. The following code has no problems executing

```elisp
(insert (all-the-icons-icon-for-dir "/home/arnaud/code/neotree" "right"))
(insert (all-the-icons-icon-for-dir "/home/arnaud/code/neotree/" "right"))
```
In both cases, the proper symbols are inserted. However, if the directory does not contain repository, things get weirder.
```elisp
;; sample_marc is a mercurial repository
(insert (all-the-icons-icon-for-dir "/home/arnaud/code/sample_marc" "right")) ;; everything ok

(insert (all-the-icons-icon-for-dir "/home/arnaud/code/sample_marc/" "right")) ;; Symbol's function definiton is void :nil
```
In this case, only the first call succeeds. It appears that all-the-icons really does't like that slash at the end of directories. This is really unfortunate as projectile gives the root of the current project **with** the trailing slash.

I looked at the code that gets called and I assume this is the function where everything goes down.
```elisp

(defun all-the-icons-icon-for-dir (dir &optional chevron padding)
  "Format an icon for DIR with CHEVRON similar to tree based directories.

If PADDING is provided, it will prepend and separate the chevron
and directory with PADDING.

Produces different symbols by inspecting DIR to distinguish
symlinks and git repositories which do not depend on the
directory contents"
  (let* ((matcher (all-the-icons-match-to-alist (file-name-base dir) all-the-icons-dir-icon-alist))
         (path (expand-file-name dir))
         (chevron (if chevron (all-the-icons-octicon (format "chevron-%s" chevron) :height 0.8 :v-adjust -0.1) ""))
         (padding (or padding "\t"))
         (icon (cond
                ((file-symlink-p path)
                 (all-the-icons-octicon "file-symlink-directory" :height 1.0))
                ((all-the-icons-dir-is-submodule path)
                 (all-the-icons-octicon "file-submodule" :height 1.0))
                ((file-exists-p (format "%s/.git" path))
                 (format "%s" (all-the-icons-octicon "repo" :height 1.1)))
                (t (apply (car matcher) (cdr matcher))))))
    (format "%s%s%s%s%s" padding chevron padding icon padding)))
```
That last case of the conditional somehow gets confused.

Also, git is not the only type of "repository" out there so I guess the check for repository should be a little bit more  sophisticated than

```elisp
(file-exists-p (format "%s/.git" path))
```
If I find the time, I will open PR

**Comment by jsmestad** [comment]
I am having this issue as well with the latest all-the-icons

**Comment by palikar** [comment]
I submitted a PR (#128). The change is very simple. If the issue is crucial for you (@jsmestad ) you can make the change in your local copy of the repository.
