### ISSUE TITLE
Weird huge icons.

### ISSUE THREAD

**Issue by Griger** [domtronn/all-the-icons.el#132]
Hi,
I have installed `all-the-icons` in order to customize `doom-modeline` with icons. The problem is that is some major modes and other options, I get some huge icons, and I want to know why and if I can fix it.
For example this is the icon that I get for a file that has changes that have not been push to the GitHub repo:

![image](https://user-images.githubusercontent.com/7707062/51527712-57675300-1e35-11e9-8dc6-3f4fae493b3f.png)

And this is the icon that appears for `*Messages*` buffer. I have seen the line `(messages-buffer-mode all-the-icons-faicon "stack-overflow" :v-adjust -0.1)` in the file `all-the-icons.elc archive`. Is there a intuitive way to set that icons to be smaller or different:

![image](https://user-images.githubusercontent.com/7707062/51527740-66e69c00-1e35-11e9-84ce-577d8b748f27.png)

Thanks a lot. Regards.

**Comment by clawoflight** [comment]
I have the same problem, let me know if you find a solution!

**Comment by clawoflight** [comment]
@Griger I'm on Arch and had `ttf-fontawesome` installed as well.
Removing that fixed this issue.
I still have wrong and missing icons though.

**Comment by Griger** [comment]
@clawoflight yes you are right... Unless we don't have the huge icons. Thanks a lot.

**Comment by Amatrelan** [comment]
Hello all, if you use that `M-x all-the-icons-install-fonts` command to install, remove the files their size is 0 so it fails to download them. Clone this repo and copy fonts `.local/share/font/` dir and it works.

**Comment by wyuenho** [comment]
Is this still happening on master?

**Comment by wyuenho** [comment]
Size 0 probably means the connection was terminated during download. You need to find out what's happening to your network.

**Comment by wyuenho** [comment]
I'm closing this issue. If you still have problems, please diagnose the problem according to [this troubleshooting guide](https://github.com/domtronn/all-the-icons.el/blob/master/README.md#troubleshooting), and open a new issue.
