### ISSUE TITLE
all the icons no longer downloading fonts or installing properly

### ISSUE THREAD

**Issue by gregf** [domtronn/all-the-icons.el#134]
OS FreeBSD 12
VERSION all-the-icons-20190215.101

I have installed the fonts several times and all the font files in ~/.local/share/fonts are empty files.

![2019-02-16-220849_1668x1014_scrot](https://user-images.githubusercontent.com/980/52907829-73dd8c00-3237-11e9-8c6c-aadb646071c0.png)

Also for fc-cache to run properly shouldn't you be running mkfontdir after adding the fonts?

**Comment by memeplex** [comment]
Same here, this was reported in doom emacs tracker some time ago:

https://github.com/hlissner/doom-emacs/issues/724

**Comment by wyuenho** [comment]
PR welcome for this. I don't have access to a FreeBSD or any custom Linux distros

**Comment by vaer-k** [comment]
It seems that `url-copy-file` in `all-the-icons.el` is not actually downloading the files, but I don't understand why.

**Comment by vaer-k** [comment]
Line 863 of `all-the-icons.el` does nothing but touch the files in place; they are all empty.
```
(mapc (lambda (font)
              (url-copy-file (format url-format font) (expand-file-name font font-dest) t))
all-the-icons-font-names)
```

**Comment by vaer-k** [comment]
If you manually download the font files from github into `~/.local/share/fonts`, they work as expected, at least in my tests using neotree.

**Comment by vaer-k** [comment]
It appears that urls for the fonts, such as "https://github.com/domtronn/all-the-icons.el/blob/master/fonts/all-the-icons.ttf?raw=true", are redirects. Maybe `url-copy-file` does not correctly handle redirects.

**Comment by mwagg** [comment]
@vaer-k that's right. This [pull request](https://github.com/domtronn/all-the-icons.el/pull/135) I sent a few days ago fixes it for me
