### ISSUE TITLE
Icons in modeline require extra space above them

### ISSUE THREAD

**Issue by noctuid** [domtronn/all-the-icons.el#136]
It seems that icons take up extra space above them in the modeline even though they don't visually take up that space. When I shrink the height of the modeline, icons will move closer to the modeline bottom, but there is still extra padding at the top. Here's an example (probably will be necessary to zoom in to ~500%).

With icons (see the extra modeline space above the light gray bar on the left):
![2019 02 24_11 15 43_-_sxhkdrc](https://user-images.githubusercontent.com/4250696/53301956-e4337100-3826-11e9-8ce6-99b61abb8216.png)

Without icons:
![2019 02 24_11 15 58_-_sxhkdrc](https://user-images.githubusercontent.com/4250696/53301957-e4337100-3826-11e9-8655-dbf4c8bab489.png)

I'm not sure if this is just because the modeline happens to require some padding and icons are bigger than other characters, but the top of the icons isn't very far above the top of other characters in the modeline. I'm not sure if anything can be done about this by this package, but it would be nice if the extra space wasn't required if possible.

See also seagle0128/doom-modeline#118.

**Comment by lerouxrgd** [comment]
I think you can change this with:
```
(setq all-the-icons-scale-factor 0.9) ; instead of default 1.2
```

**Comment by noctuid** [comment]
Looking at doom-modeline, this has to do with how it uses raise and height and isn't an issue with all-the-icons.

**Comment by lerouxrgd** [comment]
Did you find a proper way to fix it though ?

**Comment by noctuid** [comment]
Not generally. It looks fine with the scale factor as 1 and a smaller height. Changing both `all-the-icons-scale-factor` and `doom-modeline-height` in general does not work well. It results situations where icons are positioned in different areas in the modeline and extra space (e.g. one icon is kind of centered, another is all the way at the bottom of the modeline, etc.).

There are a lot of magic numbers in doom modeline (e.g. as `:height` arguments in `doom-modeline-segments.el` and `1.2` in `doom-modeline-icon-height`), and I don't know the logic behind the choices. I was able to get things to look better in some cases by messing with these values but didn't really attempt to figure anything out.

This probably warrants a separate issue for doom modeline.
