### ISSUE TITLE
macOS all icons not rendering

### ISSUE THREAD

**Issue by timlkelly** [domtronn/all-the-icons.el#141]
I installed the package by adding `(use-package all-the-icons)` to my `init.el` and when I run `(all-the-icons-insert-icons-for 'alltheicon)` to test them they all appear as a question mark inside of a box. See the screenshot. I assume this means that the fonts are not correctly installed on my computer.

Unaware of the correct directory for the fonts, I tried them in the following locations: `/Library/Fonts`, `~/Library/Fonts`, `~/.local/share/fonts`. I tried just installing via double clicking the `.ttf` in the finder. And ran `fc-cache -f -v` manually as well. I do see the fonts inside of the `Font Book` application and as well as an option in iTerm2 when picking your font. Are these not the correct directories to install the fonts?

macOS 10.13.6
emacs 26.1
iTerm2 3.2.7

![image](https://user-images.githubusercontent.com/8271737/54493558-73b8c680-489f-11e9-8c31-dfc02fbc0ce8.png)

**Comment by leomikezee** [comment]
Same problem
macOS 10.14.3
emacs 26.1
iTerm2 3.2.7

**Comment by greghendershott** [comment]
@timlkelly You didn't mention using [`M-x all-the-icons-install-fonts`](https://github.com/domtronn/all-the-icons.el#installing-fonts)?

From [its code](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L858-L859) it seems like maybe you already manually did what it does; but maybe worth trying?

Also, FWIW that code seems to prefer `(concat (getenv "HOME") "/Library/Fonts/")` a.k.a. `~/Library/Fonts`.

(I'm no authority on this. Just browsing issues before installing this package.)

**Comment by timlkelly** [comment]
I should have been more specific. I did use `M-x all-the-icons-install-fonts` for all of the directories I listed above. The only "manual" attempt was opening the `.ttf` file from the finder.

**Comment by wyuenho** [comment]
Have you read [the troubleshooting guide](https://github.com/domtronn/all-the-icons.el/blob/master/README.md#troubleshooting)?

**Comment by timlkelly** [comment]
I believe i found the issue, which is because i'm running emacs in the terminal. iTerm2 can set non ascii fonts but you can only pick one. going to go ahead and close this
