### ISSUE TITLE
Integration with helm?

### ISSUE THREAD

**Issue by vn-ki** [domtronn/all-the-icons.el#151]
Maybe not the best place to ask, but hoping that someone has suggestions.

**Comment by da-edra** [comment]
I want to know too...

**Comment by ema2159** [comment]
I'm not a user of Helm but I know this exists: https://github.com/asok/all-the-icons-ivy. Maybe you could get some inspiration from and give the community a similar package for Helm.

**Comment by andersjohansson** [comment]
Here is some work in progress that I did on this inspired by [helm-treemacs-icons](https://github.com/yyoncho/helm-treemacs-icons/):
https://gitlab.com/andersjohansson/helm-all-the-icons

**Comment by thierryvolpiatto** [comment]
Now helm have `helm-ff-icon-mode` to display icons from all-the-icons in helm-find-files.
