### ISSUE TITLE
Icon choosing

### ISSUE THREAD

**Issue by andreyorst** [domtronn/all-the-icons.el#163]
I had this issue with [doom-modeline](https://github.com/seagle0128/doom-modeline) that uses `all-the-icons` to display filetype: https://github.com/seagle0128/doom-modeline/issues/228#issuecomment-539598884

I've thought that this is `doom-modeline` issue but @seagle0128 said that all the icons is responsible to choose which icon to display, and it takes file name into account, not only the extension. Because of that my C files have wrong icon:
![image](https://user-images.githubusercontent.com/19470159/66567501-fcff5580-eb6f-11e9-9f16-18404a42c530.png)
![image](https://user-images.githubusercontent.com/19470159/66567509-0092dc80-eb70-11e9-948c-7cbf8234fd3d.png)

Can anything be done with that behavior? E.g. prefer extension filtering, and use filename filtering if there's no extension or no icon for such extension?

**Comment by HTempleman** [comment]
You could modify all-the-icons.el to specify that all instances of .c file types with the word 'test' should still use the c-line icon.

```elisp 
("-?test\\.c$"     all-the-icons-alltheicon "c-line"      :face all-the-icons-blue)
```
A more generic solution would probably require user options that conditionally ignore certain regex patterns.

**Comment by seagle0128** [comment]
Another workaround: https://github.com/seagle0128/doom-modeline/issues/228#issuecomment-540620561.

**Comment by wyuenho** [comment]
This is a bug in doom-modeline. There is an `all-the-icons-icon-for-mode` function, doom-modeline should use it instead.
