### ISSUE TITLE
No defface for all-the-icons-white

### ISSUE THREAD

**Issue by jasonh-logic2020** [domtronn/all-the-icons.el#166]
Emacs 27.0.50, all-the-icons 20190320.1809

I have a bunch of faces which inherit from it which are blowing out messages like:

```
Invalid face reference: all-the-icons-white
Invalid face attribute :inherit all-the-icons-white
```
every time my code tries to use one of them.

I haven't changed anything in that part of my init.el in a long time but I note that when I look in all-the-icons-faces.el, I don't see a block defining white. My personal extensions are new segments for erc-mode and 
https://github.com/domtronn/all-the-icons.el/blob/f996fafa5b2ea072d0ad1df9cd98acc75820f530/all-the-icons.el#L430
looks like the source of the white face.

**Comment by wyuenho** [comment]
It should be fixed now.
