### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by anmonteiro** [domtronn/all-the-icons.el#17]
Currently XML files are not recognized. Is there an existing icon we could use to present XML files?

**Comment by domtronn** [comment]
The closest thing I could find to an XML icon _(considering it doesn't actually have one)_ is this http://fontawesome.io/icon/file-code-o/

Which would be

```elisp
(all-the-icons-faicon "file-code-o")
```

I actually added this to `web-modes` mode matcher when the `web-mode-content-type` is XML, see [here](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L484-L485). So it would probably be good for the file matcher to be the same? :)

**Comment by anmonteiro** [comment]
👍  by me

**Comment by domtronn** [comment]
Pushed a file matcher 😬
