### ISSUE TITLE
Help improving Golang gopher icon

### ISSUE THREAD

**Issue by muirdm** [domtronn/all-the-icons.el#170]
Hi

I'd like to switch to this icon for Go: https://github.com/golang-samples/gopher-vector/blob/master/gopher-front.svg. The current icon is a wireframe gopher and doesn't look very good. 

If I understand correctly, all existing icons come from fonts, so they cannot have multiple colors. Are you interested in also supporting images as icons? We could include the png file in the package, or we could add Elisp to create the SVG image programmatically (attributing properly, of course).

Here is before and after images:
<img width="833" alt="Screen Shot 2019-10-27 at 1 34 32 PM" src="https://user-images.githubusercontent.com/11356572/67641300-a8bdda80-f8be-11e9-9616-f5199633a20e.png">

<img width="833" alt="Screen Shot 2019-10-27 at 1 34 53 PM" src="https://user-images.githubusercontent.com/11356572/67641303-ad828e80-f8be-11e9-94e5-63a4e96b461c.png">

**Comment by ema2159** [comment]
An easier solution would be to use the `file-icons` font's Go icon instead of the one from `all-the-icons` font which in my opinion looks much better.

**Comment by fabricekwizera** [comment]
@muirdm it looks like you have done much on your Emacs and it really looks cool. I could use your help (if you have few minutes) and tell me how you configured it. Thanks

**Comment by wyuenho** [comment]
should be fixed by 9198f3ced286749c979ee7ce6421ba2ba2485e5d now
