### ISSUE TITLE
Emacs crashes when running set-fontset-font as per troubleshooting recommendation

### ISSUE THREAD

**Issue by fperies** [domtronn/all-the-icons.el#174]
Hello,

I'm currently using Spacemacs with a RHEL7 machine and I'm getting weird icons just as below:
![image](https://user-images.githubusercontent.com/7024137/69546685-81792c80-0f94-11ea-802c-52894340f90b.png)

The output of the describe-fontset command gives me the following:
![image](https://user-images.githubusercontent.com/7024137/69546549-3eb75480-0f94-11ea-979f-199b571e0d71.png)
I guess this fontset-auto1 is built by Spacemacs and is my default???

Anyway, as per Troubleshooting section, for codes corresponding to icons I don't see any fonts related to all-the-icons:
![image](https://user-images.githubusercontent.com/7024137/69547223-77a3f900-0f95-11ea-96a7-9667be389a09.png)

Then, when I run the following command:
`(set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'append)`
Emacs crashes due to a Segmentation fault !

What am I doing wrong ?
How to get correct icons display?
Thanks

**Comment by xeijin** [comment]
@fperies I know you found another way to resolve your issue, per #80, however I was still having issues (and in-case of use to others).

I was also getting a crash when attempting to follow the instructions on the homepage. Not exactly sure why, but changing the `'append` to `'prepend` in the command fixed the issues for me.

```lisp
(set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'prepend)
(set-fontset-font t 'unicode (font-spec :family "github-octicons") nil 'prepend)
(set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'prepend)
(set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'prepend)
(set-fontset-font t 'unicode (font-spec :family "file-icons") nil 'prepend)
(set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'prepend)
```

**Comment by xeijin** [comment]
`'prepend` isn't ideal since it places the `all-the-icons` fonts above the existing `ascii` ones.

Therefore I recommend adding a unicode font with good coverage like `Symbola` and/or Google's `Noto Sans Symbols2`.

You can use something like this either directly in your config or encapsulate in a function and add it to `emacs-startup-hook`.

```elisp
  (let ((unicode-fonts (list
                        "Weather Icons"
                        "github-octicons"
                        "FontAwesome"
                        "all-the-icons"
                        "file-icons"
                        "Material Icons"
                        "Symbola"
                        "Noto Sans Symbols2")))
    (dolist (fnt unicode-fonts)
      (when (member fnt (font-family-list))
        (set-fontset-font t 'unicode fnt nil 'prepend))))
```
