### ISSUE TITLE
Icon on emacs28 seems to zoom bigger than the normal.

### ISSUE THREAD

**Issue by CanftIn** [domtronn/all-the-icons.el#188]
Hi, I have installed emacs 28 and 26 all in Windows, and find a situation before the two version.

On emacs `28.0.50`, icon of the major mode is bigger than the normal stituation.
![image](https://user-images.githubusercontent.com/26135447/76068047-63778b00-5fcb-11ea-9520-4237675f22be.png)

emacs `26.3` works normally like that:
![image](https://user-images.githubusercontent.com/26135447/76068176-a5083600-5fcb-11ea-9344-04447d77f95a.png)

And on `28.0.50`, it appears on not only the major mode icons. Other buffers or other lanuage major mode display the same problem.
![image](https://user-images.githubusercontent.com/26135447/76071094-a8ea8700-5fd0-11ea-8ae8-d95c37e5368a.png)

I've set the possible relative configuration in spacemacs:
```lisp
(defun dotspacemacs/layers ()
  (setq-default
...
   dotspacemacs-additional-packages
   '(
     all-the-icons
     all-the-icons-dired
     all-the-icons-ivy
     mode-icons
     unicode-fonts
     )
...
))

(defun dotspacemacs/user-config ()
  (setq mode-icons-change-mode-name t)
  (mode-icons-mode)
...
)
```
**platform**: Windows 10 version 1909 (inside version 18363.657)

**Comment by wyuenho** [comment]
This is an issue with emacs master, please report this to emacs-devel
