### ISSUE TITLE
Incorrect dir icons

### ISSUE THREAD

**Issue by seagle0128** [domtronn/all-the-icons.el#190]
https://github.com/domtronn/all-the-icons.el/blob/5b661c3b8722f79d1286d1c9cb0bd0e889c34082/all-the-icons.el#L804-L808

I tested with the latest version today, and found the directory icons are incorrect because of the invalid `args`. For example, 
```elisp
(apply #'all-the-icons-octicon "file-symlink-directory" args)
``` 
should be 
```elisp
(apply #'all-the-icons-octicon "file-symlink-directory" (cdr args))
```

**Comment by pbgc** [comment]
Hi.

Even with this change the folders icons are wrong!
It used to be (and still is on stable version):

![Captura de ecrã 2020-03-24, às 17 35 52](https://user-images.githubusercontent.com/180825/77458426-10d50600-6df6-11ea-85b2-347205efa64e.png)

And now:


![Captura de ecrã 2020-03-24, às 17 34 48](https://user-images.githubusercontent.com/180825/77458458-1fbbb880-6df6-11ea-8eb8-768c781db970.png)

**Comment by wyuenho** [comment]
Which package did the screenshot come from?

**Comment by pbgc** [comment]
@wyuenho sorry. I edited the original post. The package is neotree (on emacs)

**Comment by wyuenho** [comment]
Please submit a PR to https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L1267 to change the call to `all-the-icons-icon-for-dir-with-chevron`

**Comment by pbgc** [comment]
@wyuenho with that change neotree will not work with the stable all-the-icons version ...

I really think that this change on all-the icons could be made without breaking everything else ... choosing diferent names and keeping the earlier api.

**Comment by pbgc** [comment]
@wyuenho After neotree update (with the change to with-chevron) and all-the-icons-update ... we get this:

![Captura de ecrã 2020-03-24, às 22 48 20](https://user-images.githubusercontent.com/180825/77484155-b8b3f900-6e21-11ea-81f7-35eab4120132.png)

**Comment by wyuenho** [comment]
This should be fixed now
