### ISSUE TITLE
Folder icon is nil

### ISSUE THREAD

**Issue by marinov98** [domtronn/all-the-icons.el#195]
I recently reinstalled my emacs packages. Now when I open neotree the icons for files show up as usual but all the folders show up as 'nil' in both neotree and ranger. 
![screenshot_20200324_231230](https://user-images.githubusercontent.com/33673401/77498007-0aaa4e00-6e25-11ea-99fe-87e06f0db5ea.png)

OS: Linux
Distribution: Ubuntu 18.04
Emacs Version: I use snapshot so 28.05

**Comment by lkzz** [comment]
+1
no dir icon in neotree and dired

**Comment by wyuenho** [comment]
@conao3 @seagle0128 ^

**Comment by wyuenho** [comment]
This appears to be caused by https://github.com/domtronn/all-the-icons.el/pull/192

**Comment by wyuenho** [comment]
The fix should appear on melpa in a few hours

**Comment by seagle0128** [comment]
@wyuenho I took a quick look at the issue. It seems `all-the-icons-icon-for-dir-with-chevron` doesn't handle nil. I will submit another PR to review.
