### ISSUE TITLE
Modeline in demo screen shot... Please make available as a package.

### ISSUE THREAD

**Issue by jasonm23** [domtronn/all-the-icons.el#2]

**Comment by domtronn** [comment]
I've added a [Wiki Page](https://github.com/domtronn/all-the-icons.el/wiki/Mode-Line) which provides some snippets for the different parts showcased in my mode line - but most of the formatting is built on some very old and fragile Powerline code from the original 3 year old version... So I'd definitely want to clean that up if I were to release it separately.

I'm more than happy to help if you have any questions about it, but I don't know if I'll get time any time soon to create this.

**Comment by jasonm23** [comment]
I worked with the early Powerline version, forked it to make something called mainline which eventually got dissected and useful things got merged in.

Mainline was the origin of the extended separator set that most people know as Spaceline, the curves etc. pretty much the only reason I made the Powerline fork in the first place.

Donald Curtis (milky postman) picked up maintaining Powerline and he merged the separators in, and cleaned up the code a bit.

As I understand it, Spaceline is just a Powerline theme.  So the code is at least good enough to support theming.

I should look closely at your code (On phone at this time) but do you think it would work as a Powerline theme?

Are there any parts you need help with?  Your emacs.d is nicely organized and well factored so I don't think you'd have any issues, but I'm happy to lend a hand if you need it.

**Comment by CestDiego** [comment]
I would love to see spaceline improved to get these icons as well it'd be very useful.

**Comment by jasonm23** [comment]
@CestDiego I didn't say that, maybe I  misunderstand your comment? 

Spaceline https://github.com/TheBB/spaceline is a theme for Powerline - although a very extensive (and well documented one.)

My suggestion was for the Doom modeline to be extracted as a package, and perhaps it would be beneficial if it were a Powerline theme like Spaceline.

If you want all-the-icons added to Spaceline, I  recommend you open a feature request over on the Spaceline Repo. https://github.com/TheBB/spaceline

**Comment by domtronn** [comment]
Hello, I've _(finally)_ created a **Spaceline** port of my Mode Line! I've not had time to turn it into a full package yet, and I'm still not 100% happy with my code to submit it. However, if you want to try it out for yourselves the code is available here;

https://github.com/domtronn/all-the-icons.el/wiki/Spaceline

It's worth noting that I've updated the `all-the-icons.ttf` font to now include Powerline Separator characters. This means that you can then colour them correctly with sRGB colours! So you no longer get the bug with Emacs 25.1 where the XPM images are the wrong colour :)

**Comment by domtronn** [comment]
Getting a few friends to try out my Spaceline configuration, I've found that the separator colourisation is static and doesn't change based on `evil-mode` _(which I wasn't aware of because I don't use `evil-mode`)_, but would want to address this before submitting it to Melpa.
