### ISSUE TITLE
Dart icon causes 100% CPU usage

### ISSUE THREAD

**Issue by zoechi** [domtronn/all-the-icons.el#202]
The changes from #200 caused severe performance issues.

As soon as I expand a directory that contains Dart files (treemacs, dired) or scroll in a buffer of a Dart file (with `doom-modeline-icon t`)  CPU spikes at 100% for about 15-30 seconds

See https://github.com/Alexander-Miller/treemacs/issues/649 for more details.

I commented the changes of #200 out in `emacs.d/elpa/all-the-icons-xxxx` and the issue was fixed.

Any idea what could cause that?

**Comment by wyuenho** [comment]
That's weird. How's the performance with a vanilla emacs and just all-the-icons installed?

**Comment by zoechi** [comment]
with `emacs -q` and only `all-the-icons` all is perfectly fine.
As soon as I also load 
```list
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :custom((doom-modeline-icon t))
  )
```
scrolling in *.dart files causes 100% CPU utilization.

**Comment by zoechi** [comment]
The modeline does not even show the Dart icon
![emacs_dart_icon_snapshot2](https://user-images.githubusercontent.com/405837/79432595-54252d80-7fcc-11ea-83d2-d79a19e3df8f.png)

When I load and open Treemacs it shows the Dart icon

![emacs_dart_icon_snapshot](https://user-images.githubusercontent.com/405837/79431248-774edd80-7fca-11ea-84c2-79182e8bbee0.png)

When I then load `(doom-themes-treemacs-config)` Treemacs does not show the Dart icon anymore.

![emacs_dart_icon_snapshot3](https://user-images.githubusercontent.com/405837/79432796-98b0c900-7fcc-11ea-8023-6bc5bf5bfffe.png)

but now I also do not experience the 100% CPU utilization issue when I expand a directory containing Dart files in Treemacs, but still when scrolling with doom-modeline active.

Could this be some icon cache not being updated after the all-the-icons update?

**Comment by wyuenho** [comment]
I don't know man. This sounds like some weird interactions in your packages.

**Comment by zoechi** [comment]
I understand. I hoped this might have come up already because it's probably not the first time a new icon was added.
I guess I'll try to report in the doom-modeline repo instead.
Thanks a lot for your support!

**Comment by Alexander-Miller** [comment]
> When I load and open Treemacs it shows the Dart icon

FYI treemacs does not use any iconic fonts like all-the-icons, it has its own set of png files.

**Comment by zoechi** [comment]
> FYI treemacs does not use any iconic fonts like all-the-icons, it has its own set of png files.

`(doom-themes-treemacs-config)` changes icons, perhaps that's why it only reproduced with it or the doom-modeline caused this even when not shown in the treemacs buffer and no other buffer open.

**Comment by zoechi** [comment]
I can't reproduce anymore. 
There were updates the recent days (lsp-mode, treemacs, others)
Perhaps one of those fixed it.
