### ISSUE TITLE
all-the-icons-icon-for-buffer

### ISSUE THREAD

**Issue by Gahamelas** [domtronn/all-the-icons.el#203]
Hi, 

all-the-icons-icon-for-buffer function is not found. Any ideas?

**Comment by wyuenho** [comment]
No. Likely you haven't installed or loaded the package.

**Comment by Gahamelas** [comment]
Yes, I have. 
![image](https://user-images.githubusercontent.com/47029233/79428296-a36c5d80-7fce-11ea-9f99-1269dbcd4ccb.png)

**Comment by wyuenho** [comment]
`all-the-icons-icon-for-buffer` is not an autoloaded function. You need to load the entire package to get to it.

**Comment by Gahamelas** [comment]
How do I load the entire package? I install the package via melpa and added 

`(use-package all-the-icons)`

In my init file.

**Comment by wyuenho** [comment]
Then it's loaded. Type `M-:`, and then eval `(all-the-icons-icon-for-buffer )` Does it complain?

**Comment by Gahamelas** [comment]
No, it doesn't, but I can't find it via M-x. I don't know how to use it.

**Comment by wyuenho** [comment]
This isn't the regular M-x, it's Prelude. Maybe there's some limit to the suggestions? What if you search for `all-the-icons-icon-for-` ?

**Comment by Gahamelas** [comment]
It should be the same. When I look for that, it turns nothing.

**Comment by wyuenho** [comment]
I'd suggest you to look into your other packages instead. I don't use Prelude so I can't help you there.

**Comment by pradyparanjpe** [comment]
I had the same problem.

```emacs-lisp
  (use-package all-the-icons
    :if (display-graphic-p)
    :commands (all-the-icons-icon-for-buffer))
```

solved it for me.

**Comment by pradyparanjpe** [comment]
I have the same problem

- Interestingly, it happens only when I connect an emacsclient to a daemon.
- In daemon, where the issue occurs, calling any other (available) `all-the-icons-` function appears to load the `all-the-icons-icon-for-buffer`
- Given that this issue was opend 2 years ago, did the OP find a solution?

**Comment by AtomicNess123** [comment]
No :(
