### ISSUE TITLE
Icons in black and white issue

### ISSUE THREAD

**Issue by AtomicNess123** [domtronn/all-the-icons.el#204]
Hi, I can see the icons in black and white. No idea why they do not show in color.

**Comment by Knusper** [comment]
Same for me.  I am using the `zenburn` theme... 

Until I  did an update recently, everything worked fine.. But now the colours are gone.

**Comment by wyuenho** [comment]
@Knusper do you have a reproduction?

**Comment by Knusper** [comment]
What do you mean? A screenshot?

**Comment by wyuenho** [comment]
Show me a commit that resulted in black and white icons. I can't do anything if I can't reproduce the problem, since you two are the only people who complain about this.

**Comment by jacobilsoe** [comment]
Colours are gone for me too. Will see if I can pinpoint a commit.

**Comment by wyuenho** [comment]
It would be great if you could tell me under what context are the icon colors gone too. all-the-icons isn't the only package in the world that tries to display faces.

**Comment by jacobilsoe** [comment]
If I run this from the scratch buffer
```elisp
(insert (all-the-icons-icon-for-file ".gitconfig"))
```
 I get a red icon. But in dired the icon for that file is white.

**Comment by Knusper** [comment]
The only dired related things in my config  are `dired-quicksort` package
and `(setq dired-listing-switches "-alh")`.

This is how I load `all-the-icons-dired-mode`:

       (use-package all-the-icons-dired
        :ensure t
        :init
        (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))

I can confirm the observation  @jacobilsoe

I do not update regularly, but I can find the last version that worked for
me.  Will do this later.

Thanks for maintaining the package!

**Comment by Knusper** [comment]
I use `melpa` for packages.  I just went to my backups to figure out the previous version.

Right now I am running `all-the-icons-dired-20210302.1410`, the version where the colors where still displayed correctly was `all-the-icons-dired-20210119.2136`.

**Comment by wyuenho** [comment]
Turn off `all-the-icons-dired-monochrome`

**Comment by jacobilsoe** [comment]
Thanks, that brings back the old behaviour. Do you know why this new option is turned on by default?

**Comment by wyuenho** [comment]
Because dired buffers are essentially the output of `ls`, which is determined by the mode bits in the terminal. By changing the color to match the text, it's doesn't confuse the user by displaying 2 different colors on the same line, one conveys the mode, and another convey nothing.

**Comment by Knusper** [comment]
Actually, I now reverted back to the new default. I somehow think the
monochrome look is clearer..
