### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by LouisKottmann** [domtronn/all-the-icons.el#205]
Hello,

Would it be possible to update the icons used by this package?
If I read `all-the-icons-project.json` correctly, I believe they have not been updated since 2016.

I would like to use then newer YAML icons for example.

Regards,

**Comment by wyuenho** [comment]
That JSON file is only used to generate some 54 icons in the `all-the-icons.ttf` font file using Icomoon.

The `file-icons.ttf` font has recently been updated and it includes 5 YAML glyphs. However, there's currently no mapping in all-`data/data-fileicons.el` and `all-the-icons.el`. You can override the mappings in your own init file but I will not be changing the YAML mapping in this packge, as it officially does not have a logo.
