### ISSUE TITLE
How can I have the exactly the same configuration like the image please.

### ISSUE THREAD

**Issue by Anass-23** [domtronn/all-the-icons.el#208]
I would like to know how to append all these icons like the image it just looks beautiful but I tried and I can’t, like the icons of the neotree and the icons if weather GitHub ....
I would appreciate a reply please, thanks!

**Comment by KonVas** [comment]
I have the same question.

**Comment by wyuenho** [comment]
Have you read the README?

**Comment by bestlem** [comment]
It is not exactly in the readme but follow to the wiki to https://github.com/domtronn/all-the-icons.el/wiki/Mode-Line

Or for a simpler install see spaceline-all-the-icons by the author of this package https://github.com/domtronn/spaceline-all-the-icons.el
