### ISSUE TITLE
Provide an R language icon

### ISSUE THREAD

**Issue by atanasj** [domtronn/all-the-icons.el#215]
It would be great if there was an icon for files associated with the `R` language. The first example is what sublime text has. The second is what VSCode has. And the final is Emacs using `all-the-icons` for `treemacs`.

<img width="140" alt="image" src="https://user-images.githubusercontent.com/27214625/83755283-ac191000-a6b0-11ea-8443-325dc0cbcb5a.png">

<img width="217" alt="image" src="https://user-images.githubusercontent.com/27214625/83755424-e8e50700-a6b0-11ea-839b-6c27e4df0d3e.png">

<img width="238" alt="image" src="https://user-images.githubusercontent.com/27214625/83755474-fb5f4080-a6b0-11ea-816e-df345281337e.png">

**Comment by wyuenho** [comment]
PR welcome

**Comment by wyuenho** [comment]
all-the-icons already has a mapping [defined for R](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L255)

If treemacs isn't using the correct icon, it could be a bug in `treemacs-all-the-icons`. Please file a bug there.

**Comment by atanasj** [comment]
Okay, will do. Thanks @wyuenho.
