### ISSUE TITLE
Dart icon rednering as omega

### ISSUE THREAD

**Issue by wurosh** [domtronn/all-the-icons.el#217]
I ran `all-the-icons-install-fonts` and all other icons are fine, but the dart one renders as an omega with a *lot* of cushion around it like so:
![dart](https://user-images.githubusercontent.com/24733181/84983125-acaead80-b16a-11ea-9736-bd1af83e9876.png)

**Comment by dfireBird** [comment]
apparently the version `file-icons.ttf` used here doesn't have a dart-icon glyph.

**Comment by jjzmajic** [comment]
So the cushion comes from the fallback font?

**Comment by dfireBird** [comment]
I think so too!

**Comment by shackra** [comment]
I'm also experiencing this :(

![imagen](https://user-images.githubusercontent.com/1055216/101272542-c5c80c80-3752-11eb-9620-811143a4b119.png)

**Comment by wyuenho** [comment]
Can you guys check if it's #214 causing this issue?

**Comment by shackra** [comment]
> 
> 
> Can you guys check if it's #214 causing this issue?

I could rewind my git history for all-the-icons and give it a try

**Comment by wyuenho** [comment]
Should be fixed by 742aa5245278e7d125a958fad9a1dd97544ab930

**Comment by shackra** [comment]
![imagen](https://user-images.githubusercontent.com/1055216/103792255-08f2f500-5009-11eb-9374-88f4241d69c0.png)

Pulled the changes, ran `all-the-icons-install-fonts` to install on `~/.local/share/fonts`, ran `fc-cache --really-force`, restarted Emacs, and now it works fine.

Thanks!
