### ISSUE TITLE
Wrong Dart and F# File Icon

### ISSUE THREAD

**Issue by repelliuss** [domtronn/all-the-icons.el#225]
Dart file icon represented as `E in a square` and F# file icon represented as `E with an Arch icon below in a square` when `all-the-icons-insert-fileicon` used.

This problem also causes a big performance hit.

![](https://i.imgur.com/Zigp4Qd.png)

I think these issues are related with this

emacs-lsp/lsp-dart#61, opened by me
seagle0128/doom-modeline#353

**Comment by wyuenho** [comment]
This could be due to file icons fonts aren't given precedence in your fontsets. Have you tried the troubleshooting guide in the README?

**Comment by repelliuss** [comment]
Yes. I tried it and I think I'm correctly seeing `file-icons`. Hex code for Dart is `\xe698` and F# is `\xe6a7`. [Here is the **very long** describe-fontset output](https://pastebin.com/zyk7q5fe). I also tried explicitly appending and prepending `file-icons`.

I don't see the glyph for Dart when I view `fonts/file-icons.ttf` through [FontDrop!](https://fontdrop.info/) too.

**Comment by polaris64** [comment]
I am also having this problem, I cannot find the glyph `0xE698` in https://github.com/domtronn/all-the-icons.el/blob/master/fonts/file-icons.ttf. This is causing large performance hits whenever Emacs tries to display this glyph.

**Comment by erasmas** [comment]
I'm also experiencing very slow performance when opening an F# file. Had to disable icons for ivy for now. https://github.com/hlissner/doom-emacs/issues/4153#issuecomment-735450142

**Comment by shackra** [comment]
I experienced https://github.com/emacs-lsp/lsp-dart/issues/61 too

Now the icon is shown but the height is ridiculous high:

![imagen](https://user-images.githubusercontent.com/1055216/101272542-c5c80c80-3752-11eb-9620-811143a4b119.png)

**Comment by wyuenho** [comment]
Can you guys check if it's https://github.com/domtronn/all-the-icons.el/pull/214 causing this issue?

**Comment by polaris64** [comment]
For Dart I added this quick fix which replaces the icon with something that looks similar: -

```elisp
(add-to-list 'all-the-icons-data/file-icon-alist '("dart" . "\xEB29"))
```

You could do something similar for F# too until the problem is fixed.
