### ISSUE TITLE
Update the codepoints data

### ISSUE THREAD

**Issue by spacekitteh** [domtronn/all-the-icons.el#226]
All of the font codepoints should be updated. For example, Material Design Icons now has nearly 1600 code points; plus I believe that there was a reshuffle of the codepoints.

https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

**Comment by wyuenho** [comment]
I don't see a reason to update. I'm going to close this issue. Let me know when you can think of a concrete reason other than updating for update's sake.
