### ISSUE TITLE
Functions to insert icon keywords / classnames

### ISSUE THREAD

**Issue by ebpa** [domtronn/all-the-icons.el#23]
Most uses of icons in web development rely on the keywords or classnames of icons.  Interactive / visual lookup is very helpful and the ultimate goal in this context is to insert the keyword or classname(s) corresponding to that icon.

Expressing an icon in HTML for example:

```
<i class="fa fa-area-chart" aria-hidden="true"></i>
```

A generally useful function that would be useful to include in this library (maybe `all-the-icons-insert-faicon-classname`?) would insert/return "fa-area-chart".  More specific behavior like insertion of html or additional classes (like "fa") could be left to the user to accomplish with user functions / snippets.

**Comment by domtronn** [comment]
I'm not sure this is a good idea... It's not really the purpose of this package and would mean its trying to solve too much. My intention was to have it be an abstraction for inserting Icons in Emacs for things like Neotree and different Mode Line customisations, to allow people to make Emac's look modern.

And I can see the value in an auto complete framework for things like *FontAwesome* in web development, but this concept doesn't apply to _all_ the fonts in this package. I also found this https://github.com/osv/ac-html-bootstrap package which claims to contain completion data for *FontAwesome*...

Feel free to use the `data` files in this package if they're useful, and if #22 gets addressed there'll be more meta data to help, I'm also open to adding meta data to those files if it serves a purpose - But I don't think it should be the responsibility of this package to provide this, sorry! :)
