### ISSUE TITLE
Function not found `all-the-icons-fileicon`

### ISSUE THREAD

**Issue by jcs090218** [domtronn/all-the-icons.el#230]
Hi, I am trying to fix `byte-compile-warnings here, https://github.com/emacs-dashboard/emacs-dashboard/pull/256.

But I have encountered an error due to this line of code.

```el
(declare-function all-the-icons-fileicon "ext:all-the-icons.el")
```

I notice this function isn't declare inside `all-the-icons.el` yet I am able to find this function after installing. Just wonder how does the function exists but I am not able to find it inside the source file?! 😕 

Thanks!

**Comment by wyuenho** [comment]
It's a macro defined at the bottom of the file.

https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L1068
