### ISSUE TITLE
Consider using $ for more entries in all-the-icons-icon-alist

### ISSUE THREAD

**Issue by jacobilsoe** [domtronn/all-the-icons.el#234]
Many of the entries in all-the-icons-icon-alist use $ in the end of the regex but some which ought to do not.
E.g.

("\\.sh"            all-the-icons-alltheicon "terminal"             :face all-the-icons-purple)

will cause the file one.show.mp4 to match "terminal" where I would expected it to match this instead:

("\\.mp4"           all-the-icons-faicon "film"                     :face all-the-icons-blue)

which, by the way, is also missing a $ in the end.

Is there a good reason for this? I can create a PR to add $ for those entries missing it.

**Comment by wyuenho** [comment]
Those are likely mistakes. Please feel free to open a PR to fix them

**Comment by jacobilsoe** [comment]
Here you are: #235
