### ISSUE TITLE
Add ejs icon

### ISSUE THREAD

**Issue by ema2159** [domtronn/all-the-icons.el#236]
This should be quite easy and straightforward. Just add the following 
``` elisp
("\\.ejs$" all-the-icons-fileicon "ejs" :height 1.0 :v-adjust -0.1 :face all-the-icons-red)
```

**Comment by wyuenho** [comment]
Please submit a PR, preferably with a screenshot. It's not that hard to click the edit button on github.

**Comment by ema2159** [comment]
To be honest, I didn't know you could submit PRs like that! Here you go #249!

Also, I apologize if I sounded a little bit rude or something, it was not my intention. I sincerely thought I had to fork, clone, modify, commit, push etc.

**Comment by wyuenho** [comment]
If if that was the case, it's still not that hard. It takes literally minutes with magit.

**Comment by ema2159** [comment]
Ok, now you're just being unnecessarily rude, especially when somebody is offering an apology. That is no way of behaving.

**Comment by wyuenho** [comment]
😀
