### ISSUE TITLE
Lock icon bigger than the others is shifting to the left on treemacs / Add icon for toml files

### ISSUE THREAD

**Issue by ig-perez** [domtronn/all-the-icons.el#241]
Hi, thanks for maintaining this package!

Hope this issue belongs to this repo, otherwise please correct me so I can close it and create it on appropriate repo.

The lock icon used for `poetry.lock` files is bigger than the other ones and it is making the icon shift to the left as shown in below image:
![image](https://user-images.githubusercontent.com/33359427/106391504-a0a2f380-63bb-11eb-8e34-16744c906a61.png)

Also I see there is no icon for `.toml` files. These files are equivalent to the `package.json` files used in JavaScript.

Thanks!

**Comment by wyuenho** [comment]
There's no poetry.lock or any .lock file defined in this package, so it must be coming from something else. I'll add an icon to TOML files..

**Comment by wyuenho** [comment]
Closed by c795d0f0a49b1823d167a252319ac32c59152d72
