### ISSUE TITLE
all-the-svg-icons

### ISSUE THREAD

**Issue by wyuenho** [domtronn/all-the-icons.el#245]
For years now, all-the-icons has been plagued by icon misalignment issues. The fundamental reason is the icon sources give different viewBox, width, height and margins. Even if they are all the same, the icons themselves will have different aspect ratios, this is just a fact of life. My idea of improvement is listed as follows:

1. Get all the SVG sources of all the icons currently used, put them into subrepos or something
2. Remove all the margins in all of the SVGs by cropping them against the box defined by the max width, max height, min width, and min height of the paths.
3. Normalize the canvas of all the icons by setting the widths and heights to be the max(max(widths), max(heights)), and remove viewBox.
4. Rewrite all the lookup methods to point to these processed SVGs
5. Package these SVGs up somehow for Melpa

Pros:
* Fundamentally solve misalignment issues
* Remove the need to fine tune with v-adjust
* Can close a bunch of tickets
* No need to install fonts anymore

Cons:
* Should I even keep the icon fonts? If not, there's no hope of seeing these icons in emacs sessions under a term.

**Comment by kevinjfoley** [comment]
FYI there is a [package](https://github.com/rougier/emacs-svg-icon) that takes a similar approach as what's described here.

**Comment by wyuenho** [comment]
Thanks, I'm aware of it. There are a lot of things I don't like about that package, it doesn't address problem 2) and 3), loads the icons directly from URLs that aren't guaranteed to be permanent, relies on Emac's obsolete `url-retrieve` facilities to load the icons one by one and url cache to cache the icons, which doesn't lend well to packages like all-the-icons-dired, and it's meant to be maintained on elpa, which usually means it's abandonware.

**Comment by trev-dev** [comment]
I am not sure if [svg lib](https://github.com/rougier/svg-lib) could be helpful but I had thought about using it to create an alternative before finding this issue. It currently works really well for [kind-icon](https://github.com/jdtsmith/kind-icon)

**Comment by jdtsmith** [comment]
`kind-icon` author here.  I went with `svg-lib` for this precise reason.  I'm considering opening it up to allow either `svg-lib` or  `all-the-icons` (by explicit icon), or neither (for text-only badges) as the source.  One nice feature of svglib is that it regularizes the width of all icons to be 2 characters wide, which is important to achieve alignment.  Is that something all-the-icons offers?

**Comment by wyuenho** [comment]
I see I've forgotten to drop the announcement here.

https://www.reddit.com/r/emacs/comments/14c5u1w/alltheicons_svg_beta/

In short, try out the SVG branch and let me know what you think.

**Comment by jdtsmith** [comment]
Thanks, I saw it there in fact, which is what piqued my interest.  Was just wondering whether fixed (2) char-width is implemented before I gave a try.

**Comment by wyuenho** [comment]
Every icon is exactly 1 character wide. Every icon scales automatically now, which means, no more alignment issue. Read the announcements and the README>

**Comment by p00f** [comment]
@wyuenho This is amazing, thanks! There's only one issue - the icon for `lisp-interaction-mode` is huge:
![image](https://github.com/domtronn/all-the-icons.el/assets/36493671/40072d9e-d395-4af0-8602-0ef977e9e344)
