### ISSUE TITLE
GLSL file extensions

### ISSUE THREAD

**Issue by ema2159** [domtronn/all-the-icons.el#247]
Similarly to #236, GLSL (OpenGL Shading Language) file extensions are missing, but it's also straightforward to solve. Simply add the following lines to the all-the-icons.el file

``` elisp
    ;; GLSL
    ("\\.glsl$"          all-the-icons-fileicon "opengl"                :face all-the-icons-blue)
    ("\\.vert$"          all-the-icons-fileicon "opengl"                :face all-the-icons-blue)
    ("\\.frag$"          all-the-icons-fileicon "opengl"                :face all-the-icons-blue)
    ("\\.geom$"          all-the-icons-fileicon "opengl"                :face all-the-icons-blue)
```

I haven't had the time to submit a PR, but you should be able to add it fairly easily.

**Comment by wyuenho** [comment]
No thank you. The OpenGL logo does not make a very good icon. It's completely illegible in body text sizes.
Also, AFAIK, there are no commonly used icons representing these file types. The closest I can find is https://github.com/PKief/vscode-material-icon-theme/issues/597, which is still an open issue.

**Comment by ema2159** [comment]
Indeed. I just thought that it was better than nothing. Though exploring the available icons, it seems there's one named vertex-shader which could be used with different colors for representing the different shaders.

**Comment by ema2159** [comment]
Coming back to this, what about this solution:
![image](https://user-images.githubusercontent.com/17773218/114147057-97cd2180-9918-11eb-918f-15fce33345f8.png)
It is close to https://github.com/PKief/vscode-material-icon-theme/issues/597 that you mentioned.

**Comment by wyuenho** [comment]
I'd accept that if you open a PR :)

**Comment by ema2159** [comment]
Awesome! Here you go #253
