### ISSUE TITLE
all-the-icons-affixation package

### ISSUE THREAD

**Issue by bdarcus** [domtronn/all-the-icons.el#250]
I'm just an intermediary, but thought I'd call your attention to this issue at the marginalia project:

https://github.com/minad/marginalia/issues/59

The OP was asking about `all-the-icons-ivy`-like functionality for marginalia, but of one of its author replied a more appropriate route would simply be a small `all-the-icons-affixation` package to provide similar support using a feature included in Emacs 28. 

He posted [prototype code](https://github.com/minad/marginalia/issues/59#issuecomment-782416476) for just that, and [wondered](https://github.com/minad/marginalia/issues/59#issuecomment-782835747) if this project might be interested in hosting it.

**Comment by wyuenho** [comment]
This is probably best left to whoever uses marginalia. I don't use marginalia so when I see an issue come on, I wouldn't know how to deal with it. As an aside, I don't think it's fair to ask existing emacs maintainers to shoulder on even more work than there are. There's already a tremendous lack of elisp package maintainers as is, if people want something done, step up.

**Comment by bdarcus** [comment]
Fair enough. I was partly posting here in case someone else might be interested at some point.

Thanks for the work you do!

**Comment by iyefrat** [comment]
This has been implemented [here](https://github.com/iyefrat/all-the-icons-completion). It's independent of marginalia, but similarly  modifies the `affixation-function` call in `completion-metadata-get` and can be easily used in tandem.
