### ISSUE TITLE
Spaceline code from wiki doesn't work

### ISSUE THREAD

**Issue by nixmaniack** [domtronn/all-the-icons.el#26]
Tried using the code from [wiki](https://github.com/domtronn/all-the-icons.el/wiki/Spaceline) but it looks like there are some missing dependencies. 
I added `yahoo-weather` which was missing but still getting `spaceline-ml-ati` doesn't evaluate. 
If I try executing it in `ielm` I get following error.
```
*** Eval error ***  Wrong type argument: stringp, nil
```

I'm trying this with Spacemacs which includes spaceline.

**Comment by domtronn** [comment]
I'm not particularly familiar with Spacemacs, but I've had a few friends use it and there seemed to be a problem with actually evaluating the `spaceline-ml-ati` definition.

Could you try going into the `spaceline-all-the-icons` file and try running `eval-defun` on the `spaceline-compile` line? This should _hopefully_ define it and fix the issue.

If it's not that issue, could you look inside your `*Messages*` buffer and send me the output please? :)

**Comment by nixmaniack** [comment]
The function gets defined, I was actually doing `eval-buffer` just to make sure everything got defined correctly. 
I'm not sure why I wasn't getting backtrace before when the error was generated. Here it is now.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil face (:family "all-the-icons" :height 1.2) display (raise 0.0) font-lock-ignore t)
  (let ((icon (cdr (assoc icon-name all-the-icons-data/alltheicons-alist))) (other-face (if all-the-icons-color-icons (plist-get args :face) (quote default))) (height (* all-the-icons-scale-factor (or (plist-get args :height) 1.0))) (v-adjust (* all-the-icons-scale-factor (or (plist-get args :v-adjust) all-the-icons-default-adjust))) (family "all-the-icons")) (propertize icon (quote face) (if other-face (list (quote :family) family (quote :height) height (quote :inherit) other-face) (list (quote :family) family (quote :height) height)) (quote display) (list (quote raise) v-adjust) (quote font-lock-ignore) t))
  all-the-icons-alltheicon("slant-left" :v-adjust 0.0)
  spaceline-ml-ati()
  eval((spaceline-ml-ati) nil)
  eval-expression((spaceline-ml-ati) nil)
  funcall-interactively(eval-expression (spaceline-ml-ati) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

```

**Comment by domtronn** [comment]
Ahhhh, this looks like your `all-the-icons.el` package is out of date! You need to make sure that your installed package contains [these lines](https://github.com/domtronn/all-the-icons.el/blob/master/data/data-alltheicons.el#L59-L66) in the data a-lists.

What version do you have installed? Also, you'll need to reinstall the [`all-the-icons.ttf`](https://github.com/domtronn/all-the-icons.el/blob/master/fonts/all-the-icons.ttf) font as I added a new set of characters to behave as separators on the SpaceLine.

If this works, I'll add something to the Wiki stating the required version, or maybe even to the snippet itself?

**Comment by nixmaniack** [comment]
Right, I used melpa and looks like the package was old. Updated from github now. Looks beautiful now! Thanks for the those pointers and awesome package! 

<img width="1278" alt="screenshot 2016-11-19 04 08 31" src="https://cloud.githubusercontent.com/assets/542810/20449238/20f0d966-ae0e-11e6-8413-b08eaeca95b6.png">

Although `evil` and `spacemacs` will need some more love. I will see if I can improve it over the weekend if I understand it! 😈  Or may be add feature request to Spaceline itself. 
<img width="1280" alt="screenshot 2016-11-19 04 09 19" src="https://cloud.githubusercontent.com/assets/542810/20449237/20ee5f42-ae0e-11e6-868c-8a7691b5ac92.png">

**Comment by idoo** [comment]
@nixmaniack how did you fix it?

**Comment by nixmaniack** [comment]
@idoo 
Not sure what fix you are referring to. 

But as mentioned in my [previous comment](https://github.com/domtronn/all-the-icons.el/issues/26#issuecomment-261661655) I updated `all-the-icons.el` from github(update should be available on melpa as well by this time I guess) and then used following code snippet to try out.
```elisp
(setq mode-line-format '("%e" (:eval (spaceline-ml-ati))))
(spaceline-compile)
```

You can also try with code snippet mentioned on the wiki.
```elisp
(use-package spaceline-all-the-icons :after spaceline 
  :load-path "path/to/spaceline-all-the-icons")
(use-package spaceline :after powerline
  :config (setq-default mode-line-format '("%e" (:eval (spaceline-ml-ati)))))
```

If you're facing specific issue, may be I can try to help.

**Comment by idoo** [comment]
@nixmaniack I tried this fix, but it seams that it doesn't work with my current theme `apropospriate`
But I solved my problem — just disabled this separators :)

But what I found is that current wiki snippet can use only `slant` variant as separator, can you test it please to confirm?

And the last question, is weather package works for you? I've added https://github.com/emacsmirror/yahoo-weather  but it show me empty place instead of current weather :( maybe you can show your config, please?

**Comment by nixmaniack** [comment]
> I tried this fix, but it seams that it doesn't work with my current theme apropospriate
But I solved my problem — just disabled this separators :)

I was using `darkokai` but separators I had set it manually so it must be just separator issue and not theme's isssue. Great that you got it working. :)

> But what I found is that current wiki snippet can use only slant variant as separator, can you test it please to confirm?

Well it works with `slant`,`arrow`, `cup` and `wave` separators, so yes your observation is correct that it doesn't work will all separators defined by powerline. May be you can file an issue to add support for other seprators [as I see](https://github.com/domtronn/all-the-icons.el/blob/1e4a1a0b53ffcb427fdbc6d13ee6e9c8d23e6216/data/data-alltheicons.el#L59-L66) only those four are currently defined by all-the-icons.

> And the last question, is weather package works for you? I've added https://github.com/emacsmirror/yahoo-weather but it show me empty place instead of current weather :( maybe you can show your config, please?

Regarding weather, I installed `yahoo-weather` package from melpa and have this in my config. 
```elisp
(use-package yahoo-weather
  :init 
  (setq yahoo-weather-location "Pune")
  (yahoo-weather-mode))
```

I don't have any more configuration related to all-the-icons it seems. I did do some minor changes related neotree, dired which landed in upstream.

**Comment by idoo** [comment]
@nixmaniack it retrieving information, but still doesn't show it :(

**Comment by nixmaniack** [comment]
Okay, I think I know why.
Can you do following and see if it works? 
1. `M-x` `spaceline-toggle-ati-suntime-on` `RET`
2. `M-x` `spaceline-toggle-ati-weather-on` `RET`

The `enabled` property of weather and time segment is `nil`. You can changed it (or remove that statement which defaults to true) to `t` to have to enabled by default.

**Comment by idoo** [comment]
@nixmaniack sorry, but it's still doesn't works for me :(

**Comment by nixmaniack** [comment]
@idoo My current spacemacs setup doesn't have spaceline enabled, I'm afraid I can't help at this time.
