### ISSUE TITLE
all-the-icons not working inside of "string" or when yanking

### ISSUE THREAD

**Issue by XMPuff** [domtronn/all-the-icons.el#261]
Hello everyone,

I'm relatively knew to both Emacs and GitHub so I hope I am doing this right and you can all bare with my incompetence.
So I got the all-the-icons package all setup and it is partly working. I can use all the icons inside the editor and my doom-modeline is also working fine with the icons.

However, if I try to use icons inside of a string, they don't show up. Also, if I place an icon using the M-x all-the-icons ... command (which works properly) and then try to copy it, it will also not work. What am I doing wrong here?

I am using Emacs 27.1 inside of cygwin64 on a Windows 10 System.

Thanks in advance

**Comment by wyuenho** [comment]
The string this package returns are [propertized](https://www.gnu.org/software/emacs/manual/html_node/elisp/Changing-Properties.html).  When you yank an all-the-icons propertized string, the `font-lock-face` is excluded and so they show a different character. You can read about this from `M-x describe-function RET yank` and `M-x describe-variable RET yank-excluded-properties`

**Comment by zrquan** [comment]
So... can anyone briefly explain how to use icons inside a elisp string? 😵

It work fine on macOS but invisiable on Windows.
