### ISSUE TITLE
Melpa 20210603.1312 gives error with NeoTree

### ISSUE THREAD

**Issue by pbgc** [domtronn/all-the-icons.el#269]
Hi,

I've been using all-the-icons with NeoTree, Projectile and perspective ... to give me a really nice experience and working great.

Today I upgraded all-the-icons to 20210603.1312 and started having the error: "apply: Wrong type argument: char-or-string-p, nil" and the integration fails (neotree does not change to show the correct project content).

If I disable all-the-icons integration on neotree by commenting the line in my init.el:

(setq neo-theme (if (display-graphic-p) 'icons 'arrow))

OR change to all-the-icons 4.0.1 on melpa stable ... everything works like always.

Thanks in advance

Pedro Costa

**Comment by wyuenho** [comment]
Should be fixed by d9ad756066c8a82d49e56d5248c74caa53827b8f now

**Comment by mbarton98** [comment]
I can confirm this fixes the same error I got with dired. Thanks for fixing it before I realized what was causing it.
