### ISSUE TITLE
fonts dosent work for me (osx 10.12.1)

### ISSUE THREAD

**Issue by motecshine** [domtronn/all-the-icons.el#27]
![image](https://cloud.githubusercontent.com/assets/7615270/21147452/0ad6e0e0-c190-11e6-9f02-cef74b29fbea.png)

**Comment by domtronn** [comment]
I'm still trying to find someone with a Mac on OSX 10.12, everyone I know is still on El Capitan, so I can't reproduce this _just yet_. I'll keep you updated when I know more.

**Comment by domtronn** [comment]
I've just tried this on 2 OSX 10.12.1 Macbooks _(a Macbook and an old Macbook Pro)_ and whilst I get the same error when installing the font, this doesn't actually mean `all-the-icons` doesn't work. I'm only guessing, but it looks like OSX 10.12.1 shows the full unicode set of characters including any gaps. 

For example, the `.ttf` files I provide only include icons in the range `80` to `100` so icons `0` to `80` are basically undefined, and my guess is Sierra is trying to display these..

Could you please install the fonts anyway and see if you have any problems with `all-the-icons` after they're installed? :) It seemed to work fine for me once you load it in Emacs.

You can test the icons are display properly by calling the following functions inside `*scratch*` buffer

```el
(all-the-icons-insert-icons-for 'alltheicon)
(all-the-icons-insert-icons-for 'fileicon)
(all-the-icons-insert-icons-for 'octicon)
(all-the-icons-insert-icons-for 'wicon)
(all-the-icons-insert-icons-for 'faicon)
```

**Comment by motecshine** [comment]
@domtronn   some fonts 
![image](https://cloud.githubusercontent.com/assets/7615270/21938813/d68944ec-d9f7-11e6-847a-2f02f5bcf996.png)

**Comment by lix90** [comment]
@motecshine @domtronn Hi, I also encounter this problem of `octicons.ttf`

<img width="388" alt="screen shot 2017-02-11 at 16 20 32" src="https://cloud.githubusercontent.com/assets/15372270/22852385/146b0108-f076-11e6-9320-6c06df780297.png">

**Comment by domtronn** [comment]
So I maintain a mapping between the icon names and the unicode strings that represent them, but those unicode strings can change between each version of the font. That's why I include a specific locked down version of Octicons _(and the other fonts)_ with the package so that the unicode strings match up.

Are you both on OSX 10.12.1? And you've both tried installing the [Octicons.ttf](https://github.com/domtronn/all-the-icons.el/blob/master/fonts/octicons.ttf) I provide? I think it always displays the Octocat things when you try to install the font...

@lix90 What happens when you run `(all-the-icons-insert-icons-for 'octicon)` inside a `fundamental-mode` buffer?

**Comment by lix90** [comment]
Thank you @domtronn I think the problem has been solved. btw, my macbook is OSX 10.11.5. But it works now after I installed Octicons.tff you provide in the package.

<img width="388" alt="screen shot 2017-02-11 at 20 42 40" src="https://cloud.githubusercontent.com/assets/15372270/22853822/be251a2a-f09a-11e6-9c7b-7e45d6dbef94.png">

**Comment by motecshine** [comment]
this [octicons ](https://github.com/Yelp/yelp.github.io/blob/master/fonts/octicons.ttf) is normal, thanks @lix90 @domtronn

**Comment by lix90** [comment]
@motecshine the octicons from yelp's repo is not compatible with all-the-icons. The octicons.ttf in all-the-icons is fine except for the strange preview of fonts.

> So I maintain a mapping between the icon names and the unicode strings that represent them, but those unicode strings can change between each version of the font. That's why I include a specific locked down version of Octicons (and the other fonts) with the package so that the unicode strings match up.

**Comment by domtronn** [comment]
I've added a new function in `v2.5.0` which will install _all_ correct fonts for you for the latest version called `all-the-icons-install-fonts`.

Hopefully this should mean people don't have issues in the future with incorrect fonts :)

**Comment by mahloun** [comment]
Sorry @domtronn, I still have got the issue mentioned above. ![picture](https://www.dropbox.com/s/cctr338jd6hvrub/Capture%20d%27%C3%A9cran%202017-06-17%2019.23.47.png?dl=1)

**Comment by stardiviner** [comment]
I have the same issue on macOS on most fonts in all-the-icons.
