### ISSUE TITLE
Display the icons very slowly

### ISSUE THREAD

**Issue by zchtoy** [domtronn/all-the-icons.el#28]
I use Emacs25.1+windows10
When i use all-the-icons with neotree wo all-the-icons-dired ,while call neotree-toggle or dired(C-x d),the emacs become very slow.

the config is 

(require 'all-the-icons)
(require 'all-the-icons-dired)
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)

**Comment by domtronn** [comment]
I will have a look at this when I get home this evening. I have a Windows 10 machine at home and will see if I can reproduce this :)

**Comment by zchtoy** [comment]
Thank you very much for your confirm

**Comment by domtronn** [comment]
I had a look at this last night, and unfortunately, I _was_ able to reproduce this... :(

For me, it seemed more than capable at rendering the view, the Neotree finder showed quickly. However, it's the navigation in the buffer that acts slowly. I also tried inserting all of the different icon sets into an empty `*scratch*` buffer and found the same thing happened when there were _a lot_ of icons in the buffer... 

I called `(all-the-icons-insert-icons-for 'alltheicon)` and this inserted ~65 icon... And in _this_ case it was fine and didn't slow down... The other icon sets did slow down drastically.

I also tried modifying the Neotree code to only use icons for files, and only render 5 files, but this was still slowed down... 

So unfortunately, I don't really have any information that can help :( I don't much about how Windows font rendering works... I will try the

* Same tests without colorizing the icons to see if those extra display properties have an impact.
* Try installing Emacs 24.X to see if its something in 25

I will keep investigating and let you know if I find anything! Sorry you're having this problem...

**Comment by zchtoy** [comment]
Hi @domtronn  i had installed spacemacs at the same situation,and now it can show all the icons in neotree and dired in normaly

**Comment by domtronn** [comment]
Hi @zchtoy, I'm glad this is working for you now! It's strange that it works in Spacemacs... Thanks for the info. I'm probably going to investigate this a lot bit further with different versions of Emacs on Windows to see what I can find.

However, are you happy if I resolve this issue now?

**Comment by zchtoy** [comment]
Hi @domtronn I,m very glad if you resolve this issue. If you resolve it I will use emacs without  spacemacs

**Comment by sho-87** [comment]
I'm getting the same issue with neotree and would rather not have to install spacemacs just to get this working. Any thoughts on what spacemacs might be doing to get this working correctly?

**Comment by Kungsgeten** [comment]
Try to add this to your init file:

`(setq inhibit-compacting-font-caches t)`

**Comment by sho-87** [comment]
that seems to have fixed the lag, thanks!

**Comment by domtronn** [comment]
That's really cool, thanks for posting this @Kungsgeten! I didn't know that was a thing but I'll update the `README.md` with a mention of this for Windows/Slow renders :)

**Comment by Kungsgeten** [comment]
Yes it isn't very well known unfortunately. I found out about it after googling for a while, but it is well hidden.

**Comment by domtronn** [comment]
Closing this now, as we now have a working improvement/solution 🎉

**Comment by shankarpdy** [comment]
I also the same slowness issue with Windows10+all-the-icon,
Setting this help and back to normal
(setq inhibit-compacting-font-caches t)

Thanks a ton.
