### ISSUE TITLE
Strange separator rendering

### ISSUE THREAD

**Issue by onc** [domtronn/all-the-icons.el#29]
First thank you for your great work. You spaceline config looks great and I would love to have the same, but I get some strange rendering issues.
<img width="762" alt="screen shot 2016-12-20 at 21 55 36" src="https://cloud.githubusercontent.com/assets/4600010/21367614/13370d4a-c6ff-11e6-926a-b97e58e65288.png">
I tried to play around using different fonts, sizes and tweaking numbers in your theme, but could not figure out, why this happens. Any ideas?

My config can be found [here](https://github.com/onc/dotfiles/tree/master/emacs)

**Comment by domtronn** [comment]
Hi there, I've got a couple of questions...

* What theme do you use?
* Do you use Spacemacs?

Lastly, I've got a little function which removes the padding on the mode line, could you try running it to see if it makes a difference? :)

```el
(defun remove-mode-line-box (&rest args)
  (set-face-attribute 'mode-line nil :box nil :underline nil)
  (set-face-attribute 'mode-line-inactive nil :box nil :underline nil))
```

Otherwise, I'll have a look over your config and see if I can reproduce this and advice!

**Comment by onc** [comment]
hey,

thank you for your quick reply.

I'm using a custom theme, generated using base16-builder.
The theme can be found [here](https://gist.github.com/onc/94badf1686a3608784846b3ffbe509d5).

I tried some other themes like womat, but got the same issue.

For emacs I'm using the version from Yamamoto Mitsuharu with his mac-specific patches. But I also tried the "basic" version without the patches and got the same...

I tried using your function the same way you do in your config, but still the same :(

**Comment by idoo** [comment]
@onc please let me know, how did you fixed it?

**Comment by onc** [comment]
hey @idoo,

I was not able to fix it. but I also had no time to look into it in too much detail.
today I'm trying a second attempt to get it working.

I disabled my entire config to find the problem. currently I have another issue:
The mode-line is rendered correctly, but only on inactive buffers.

![screen shot 2017-01-30 at 14 07 34](https://cloud.githubusercontent.com/assets/4600010/22426617/3e335ffa-e700-11e6-91cc-55a319fe12b0.png)

On active buffers, there is some kind of overlay in front...

![screen shot 2017-01-30 at 14 06 07](https://cloud.githubusercontent.com/assets/4600010/22426608/343f52c4-e700-11e6-9d86-f77860bb284d.png)

I get this overlay in all themes. The color of this overlay is depending on this line in the configuration of my theme:

``` emacs-lisp
`(mode-line ((t (:background ,base09 :foreground ,base04 :box nil))))
```

If I modify the `background` color, the overlay appears in a different color...

**Comment by idoo** [comment]
@onc looks like I have same issue http://take.ms/NZmjt

**Comment by onc** [comment]
I found it! 2 things:

take a look at your messages buffer. After I disabled all my config, spaceline-all-the-icons was not able to find flycheck. this caused the issue of the overlay o.O

after enabling flycheck, my mode-line was find.

![screen shot 2017-01-30 at 15 44 50](https://cloud.githubusercontent.com/assets/4600010/22427338/117300d0-e703-11e6-8041-730d21390917.png)

I reenabled the rest of my config and got the same issue as shown in my first image from december.
So i made bisection on my `init.el` and found the bad boy: `mode-icons`

If in enable mode-icons-mode, the mode-line is broken, if i disable it it looks just fine.

This is my current spaceline config:

``` emacs-lisp
;; Icon package
(use-package all-the-icons
  :ensure t
  :config
  (use-package all-the-icons-dired
    :ensure t
    :init (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)))


;; Requirement of Spaceline
(use-package powerline
  :ensure t
  :config

  ;; Mode line
  (use-package spaceline-config
    :ensure spaceline
    :config

    ;; Custom (iconized) spaceline theme
    (use-package spaceline-all-the-icons
      :load-path "spaceline"
      :config
      (use-package spaceline-colors
        :load-path "spaceline"
        :init (add-hook 'after-init-hook 'spaceline-update-faces)
        :config (advice-add 'load-theme :after 'spaceline-update-faces)

        (setq-default powerline-default-separator 'nil)
        (setq-default mode-line-format '("%e" (:eval (spaceline-ml-ati))))))))
```

`spaceline-colors.el` and `spaceline-all-the-icons.el` are in `~/.emacs.d/spaceline/~`

**Comment by domtronn** [comment]
@onc @idoo Thank you both for looking into this, really useful information! Sorry I couldn't be more help... But I might work on the `spaceline-all-the-icons` package a bit more and hopefully fix these issues before trying to add it to Melpa 👍
