### ISSUE TITLE
Support for lsp-mode

### ISSUE THREAD

**Issue by raphaal** [domtronn/all-the-icons.el#294]
Will it be possible to provide icons for [lsp-mode](https://emacs-lsp.github.io/lsp-mode/)? I mean [lsp-headerline](https://emacs-lsp.github.io/lsp-mode/page/main-features/#breadcrumb-on-headerline) and [lsp-treemacs](https://github.com/emacs-lsp/lsp-treemacs).
I've noticed that it requires to create new icons (see [https://github.com/emacs-lsp/lsp-treemacs/blob/master/lsp-treemacs-themes.el](https://github.com/emacs-lsp/lsp-treemacs/blob/master/lsp-treemacs-themes.el)).

**Comment by wyuenho** [comment]
You can already use [treemacs-all-the-icons](https://github.com/Alexander-Miller/treemacs/blob/b18a05b1f62074a40e6011d83cd4c92cbee040dd/src/extra/treemacs-all-the-icons.el).

headerline already uses all-the-icons.
