### ISSUE TITLE
How to bind my custom typescript-tsx-mode for tsx icon

### ISSUE THREAD

**Issue by danielpza** [domtronn/all-the-icons.el#295]
I have a derived mode for typescript + react called `typescript-tsx-mode`, when I do `(all-the-icons-icon-for-mode 'typescript-tsx-mode)` I get the typescript icon instead of the `tsx` one.

Is there a way to assign this new mode to the tsx icon?

this is how I'm defining the mode:

```elisp
(define-derived-mode typescript-tsx-mode typescript-mode "tsx")
```

**Comment by wyuenho** [comment]
There's already support for typescript-tsx-mode
