### ISSUE TITLE
Can't change go icon size

### ISSUE THREAD

**Issue by nlamirault** [domtronn/all-the-icons.el#3]
Hi,
i try to insert the golang icon .
In go-mode, i can't use the function  all-the-icons-data/devicons-alist , but it works with "go" : 

```
ELISP> (assoc "go-mode" all-the-icons-data/devicons-alist)
nil
ELISP> (assoc "go" all-the-icons-data/devicons-alist)
 (assoc "go" all-the-icons-data/devicons-alist)
("go" . "")
ELISP> (all-the-icons-devicon "go")
#("" 0 1
  (display
   (raise -0.24)
   face
   (:family "icomoon" :height 1.2 :inherit nil)))
ELISP> (propertize (all-the-icons-devicon "go")
            'face `(:family ,(all-the-icons-devicon-family) :height 0.1)
            'display '(raise -0.1))
#("" 0 1
  (face
   (:family "icomoon" :height 0.1)
   display
   (raise -0.1)))
```

But in the buffer, the icon is the same size for *(all-the-icons-devicon "go")* and *(propertize ...)*

any idead how to fix that ?
Thanks

**Comment by domtronn** [comment]
`all-the-icons-data/devicon-alist)` is a variable, not a function, so you would want to do `(describe-variable 'all-the-icons-data/devicon-alist)`

And from my experience, major language modes tend to force the height of propertized text to be the line height. If you changed the buffer to `fundamental-mode`, then you would be able to edit the height _etc._

**Comment by nlamirault** [comment]
I try a simple modeline (See here [1]).
The result is [2].
Any idea ?

[1] : https://github.com/nlamirault/scame/blob/develop/src/scame/core/08_scame_modeline.el
[2] : http://www.hostingpics.net/viewer.php?id=253569201609141122331280x800scrot.png

**Comment by nlamirault** [comment]
See #6

**Comment by domtronn** [comment]
@nlamirault Issue #6 Seems to be fixed now! Please [this comment](https://github.com/domtronn/all-the-icons.el/issues/6#issuecomment-247768954) for details on updating...

Basically you'll want to install the new `all-the-icons.ttf` font from [here](https://github.com/domtronn/all-the-icons.el/tree/master/fonts/all-the-icons.ttf). This should include all the icons that were previously too big but fixed :)
