### ISSUE TITLE
Getting different (incorrect) icons when using eval-expression

### ISSUE THREAD

**Issue by shellhead** [domtronn/all-the-icons.el#30]
I was playing around with this package a bit and spent some time with this oddity. 

If I run `(all-the-icons-icon-for-file "foo.rb")` using `eval-expression`, then I often get back the incorrect icon. What I get back varies depending on what font family is installed, I'm currently getting back a weather icon, but have also seen a four arrows and what looks like a wizard a staff. However, when I run `(insert (all-the-icons-icon-for-file "foo.rb"))`, the expected ruby icon is inserted in the buffer.

**Comment by domtronn** [comment]
Yeah, I'm very aware of this problem. It's all to do with the [propertization](https://www.gnu.org/software/emacs/manual/html_node/elisp/Changing-Properties.html) of the string. In normal buffers, you basically set the `font-family` around the unicode character using points in the buffer, _i.e._ in an empty buffer, calling `(insert (all-the-icons-icon-for-file "foo.rb"))` will insert a unicode character and propertize _(set)_ the `font-family` between points 0 & 1 to be the appropriate font whilst the rest of the buffer will be the normal `font-family`...

So, when calling the function using `eval-expression` it will output in the minibuffer which doesn't render propertized text, and instead displays what the propertized string would be.

You'll notice that the output in the minibuffer looks like

```el
#("" 0 1 (font-lock-ignore t display (raise 0.0) face (:family "github-octicons" :height 1.2 :inherit all-the-icons-lred)))
```

The first thing in the list is the unicode character which renders differently based on the font. The next two are the points to display the text over _(relative to the character)_. Then you'll see that there's a `font-lock-ignore` property which tells it to ignore the font locking _(syntax highlighting)_ in a buffer. Lastly, you'll see the `face` property which has a `:family` of `"github-octicons"` this is the bit that tells Emacs what font to use when rendering the unicode character.

I hope this makes a bit more sense? But I don't know how to make the minibuffer render the propertized text - I tend to just use a `*scratch*` buffer and insert the icons for testing.

**Comment by shellhead** [comment]
Yes, thank you for clearing that up!

Is it something worth pointing out in the `README.md`? I may be the only one foolish enough to fall into this and its not worth noting.

**Comment by domtronn** [comment]
No you're right, it's definitely worth mentioning if people might not expect it! 

I'll add something to the Readme :)
