### ISSUE TITLE
can't change default colors of icons

### ISSUE THREAD

**Issue by onlinespending** [domtronn/all-the-icons.el#302]
I've tried directly editing the all-the-icons.el file to choose a different color for the python modes (from dblue to lred for instance) and even tried editing the definition of dblue in the all-the-icons-faces.el file, and yet Emacs 27.2 still displays the python icons in dark blue. I've edited these files directly under my .emacs.d/elpa directory. Is there some sort of cache that it's using that could explain this behavior?

**Comment by jacobilsoe** [comment]
Are you sure the elc file has been regenerated? If not try and delete that as well.

**Comment by bsferrazza** [comment]
@jacobilsoe sorry for the delay in responding. Same person, difference account. You're absolutely correct. Deleting the .elc file did the trick
