### ISSUE TITLE
How-to: add custom icon

### ISSUE THREAD

**Issue by sebastiaanspeck** [domtronn/all-the-icons.el#306]
Hi,

Earlier today I opened a pull request to add a icon for .magik-files and for the magik-session-mode and magik-cb-mode (https://melpa.org/#/magik-mode). 
The pull request got rejected, but how can I customize the mapping without having to edit the downloaded package in my elpa-folder?

Thanks in advance

**Comment by sebastiaanspeck** [comment]
#305

**Comment by wyuenho** [comment]
You update the lists in your init file before calling any of the `all-the-icons-*` functions.
