### ISSUE TITLE
[help] all-the-icons don't show on mac terminal

### ISSUE THREAD

**Issue by abdelbk** [domtronn/all-the-icons.el#310]
Im new to Emacs and having trouble making icons to show

My config is a simple as this :
```
(use-package all-the-icons                                                                                                                                                      
 :if (display-graphic-p))
```
I already ran `all-the-icons-install-fonts` and I can locate them inside the Library/Fonts folder.

<img width="305" alt="Capture d’écran 2022-03-12 à 22 41 55" src="https://user-images.githubusercontent.com/2431171/158058299-847e348d-b6aa-4385-bca9-9e31bc9cd2dd.png">

<img width="275" alt="Capture d’écran 2022-03-13 à 12 59 09" src="https://user-images.githubusercontent.com/2431171/158058368-c1efc7b1-aa52-4243-ad13-6b2842f4bd6d.png">

Is there something I'm missing ?

**Comment by wyuenho** [comment]
`display-graphic-p` means all the icons is only loaded initialized when you run emacs as a GUI.
