### ISSUE TITLE
Can all-the-icons support VSCode icons?

### ISSUE THREAD

**Issue by taquangtrung** [domtronn/all-the-icons.el#321]
Hi,

I'm currently working on a PR in helm-imenu (https://github.com/emacs-helm/helm/pull/2516) to display icons for source code item (methods, function, variables, etc).

However, there are many source code item icons, like the one from [VSCode icons](https://github.com/microsoft/vscode-icons) are missing from this `all-the-icons` package, especially the one from the IntelliSense section:

![https://user-images.githubusercontent.com/35271042/63165742-986ec100-c02c-11e9-874a-bb4f5897ac5a.png](https://user-images.githubusercontent.com/35271042/63165742-986ec100-c02c-11e9-874a-bb4f5897ac5a.png)

Can you advise if `all-the-icons` can support VSCode icons?

Thank you!

**Comment by wyuenho** [comment]
Give the SVG branch a try
