### ISSUE TITLE
Some octicon icons not displayed

### ISSUE THREAD

**Issue by deb75** [domtronn/all-the-icons.el#324]
Hello,

I opened [this issue](https://github.com/emacs-lsp/lsp-mode/issues/3571) in `lsp` repository,
but I think it is more directly related to `all-the-icons` (and my config) than `lsp`.

To sum up, if I do : 
```elisp
(all-the-icons-octicon "light-bulb")
```

in a scratch with lisp-interaction-mode, I get : 
```elisp
﻿#("" 0 1 (face (:family "github-octicons" :height 1.2) font-lock-face (:family "github-octicons" :height 1.2) display (raise -0.24) rear-nonsticky t))
```

I am unable to understand if this is an error or the expected result. Only the icon code is displayed as in the referenced bug.

This is surprising as if I do
```elisp
Alt-x all-the-icon-octicon RET light-bulb RET
```
I do get ﻿a nice light bulb in the same buffer.

Could you explain me why it works in some cases and not in others ?

Regards

**Comment by wyuenho** [comment]
What you are looking at is an emacs representation of a [propertized string](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Properties.html). The string at the beginning is not propertized, so depending on what faces is applied to the lisp-interaction-mode REPL, that string may not be what you will expect. If you [insert](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L60) that propertized result into a blank buffer, you may see what you expect.
