### ISSUE TITLE
Adding a new icon font? ClockFace

### ISSUE THREAD

**Issue by jasonm23** [domtronn/all-the-icons.el#334]
https://github.com/ocodo/ClockFace-font

I've published a set of icon fonts that I'd like to add to all the icons.

Each icon in tbe fonts is a clock face showing time approximated to 5min.

Unicode codepoints run from 0xF0000

**Comment by wyuenho** [comment]
I'm going to close this one. While this icon set is useful on the first glance, it leaves much to be desired, not the least of which is the inability to display the exact time by the minute despite this icon set having 5 min increments. I have a better idea to support an actual animated clock with an icon in emacs.
