### ISSUE TITLE
Flycheck status: Add info messages to spaceline

### ISSUE THREAD

**Issue by CSRaghunandan** [domtronn/all-the-icons.el#34]
it looks like `all-the-icons-spaceline.el` completely ignores any *info* messages by flycheck. It would make sense to add them to the list of issues or add a separate segment for info messages for flycheck.

**Comment by domtronn** [comment]
Hi @CSRaghunandan, thanks for this suggestion, I just noticed myself that the `flycheck` segment was broken! 😅  I'm uploading a fix to the Wiki now, but I've never come across _info_ messages before so I haven't been able to check this, but this snippet might work for you?

```el
(spaceline-define-segment
    ati-flycheck-info "An `all-the-icons' representaiton of `flycheck-status' info messages"
    (let-alist flycheck-current-errors
      (when .info
        (let ((text (format "%s%s" (all-the-icons-faicon "info") .info)))
          (propertize (format "%s" text)
                      'face f
                      'help-echo "Show Flycheck Errors"
                      'display '(raise 0.2)
                      'mouse-face '(:box 1)
                      'local-map (make-mode-line-mouse-map 'mouse-1 (lambda () (interactive) (flycheck-list-errors)))))))
    :when (and active (boundp 'flycheck-last-status-change) flycheck-current-errors) :tight t)
```

Just add `ati-flycheck-info` to the `spaceline-compile` at the bottom of the file. :) I'm going to upload this change to the Wiki version as well

**Comment by domtronn** [comment]
@CSRaghunandan You also mentioned the Buffer Position part of the mode line? If you're still interested in this, I've added a snippet to help with this as well... I rewrote the _HUD_ indicator to work with sRGB colours

```el
(spaceline-define-segment
    ati-hud "Display position through buffer as an XPM image"
    (let ((color1 (face-foreground highlight-face))
          (height (or powerline-height (frame-char-height)))
          pmax
          pmin
          (ws (window-start))
          (we (window-end)))
      (save-restriction
        (widen)
        (setq pmax (point-max))
        (setq pmin (point-min)))
      (propertize " "
                  'display (pl/percent-xpm height pmax pmin we ws (* (frame-char-width) 3) color1 nil)
                  'face highlight-face))
    :tight t :when active :enabled t)
```

And then add

```el
((ati-hud buffer-position) :separator " ")
```

To the `spaceline-compile` wherever you would like it to be rendered 😃 Also, you can swap `highlight-face` for `default-face`, `other-face` depending on where you place it in the mode line.

**Comment by CSRaghunandan** [comment]
@domtronn , thanks for your quick replies, but I guess I'll end up using the default flycheck indicators provided by spaceline. I am on a 13in RMBP and every little screen estate matters in the mode-line or it will look overly cluttered when I've open 2 buffers in a vertical split :(

A few suggestions:
* why use `" . "` as separators? when we just use a single space as a separators. That would work just as fine and take 2 characters less :)
* `ati-buffer-id` for `spaceline-all-the-icons` can take too much space if we are on a deeply nested file in a project. I really wish I had a desktop with a big ass display, but alas. I'm stuck with my 13in screen for now. And the font is almost intangible on my screen. (I guess this is due to my font settings?)
* We can also remove the extra `"| "` and `" |"` enclosing the `ati-projectile`. Instead why not make the face **bold** (saves 4 characters of space! and does the job right?)
* I wish I could somehow throw in `minor-modes` segment, but I just don't have enough space on the mode-line. Maybe we could do something about that?

**Comment by domtronn** [comment]
@CSRaghunandan I've now fully created [`spaceline-all-the-icons`](https://github.com/domtronn/spaceline-all-the-icons.el) theme! And I've taken a lot of this discussion into account, including the concept of the narrow version of the mode line.

Although, I had a couple of questions, you mentioned the `erc-track` segment, but I don't use it so I don't know what it's based on or what information it gives you? Or what information you'd like for IRC channels? 😃

**Comment by CSRaghunandan** [comment]
@domtronn Hey thanks a lot for the new package. I'll surely check this out in my spare time.

And the `erc-track` segment just indicates the name of the irc channel whenever someone mentions your nick in an active erc channel in emacs.
Eg: if I've opened #emacs in erc and if my nick gets mentioned, #emacs would be shown in the spaceline segment

**Comment by domtronn** [comment]
This has been implemented in [`spaceline-all-the-icons`](https://github.com/domtronn/spaceline-all-the-icons.el).

Other suggested segments have been raised as issues.

**Comment by CSRaghunandan** [comment]
One more segment could be for the number of multiple cursors. I've minor-mode lighters disabled in spaceline. So, I've no way of knowing how many multiple cursors I've. So, I added this [segment](https://github.com/CSRaghunandan/.emacs.d/blob/d088cfc5157d2506d13bd926743d86b6a6ec1473/setup-files/setup-mode-line.el#L33)  to my emacs config. 

But this is useful only if someone has disabled the minor mode segment for spaceline :)
