### ISSUE TITLE
add major mode icon for mastodon.el

### ISSUE THREAD

**Issue by mooseyboots** [domtronn/all-the-icons.el#346]
hi, and thanks for all your work on this sexy pkg.

i wonder how to add an icon for mastodon.el (https://codeberg.org/martianh/mastodon.el)? i would just like it to display in the modeline when `mastodon-mode` is active. i've seen the mode line snippet in the wiki but it's unclear how to add new icons.

an example of the icon can be found at https://joinmastodon.org.

**Comment by wyuenho** [comment]
All URL related functions will be gone in the next major version.
