### ISSUE TITLE
The lambda icon for Scheme has uneven height

### ISSUE THREAD

**Issue by dadinn** [domtronn/all-the-icons.el#357]
This makes buffer mode-lines uneven, as it can be seen in this picture:

![image](https://user-images.githubusercontent.com/521910/234571715-e2d0b40f-2c3a-4d67-bfed-043576bb75a5.png)

As it could be seen, I am using [doom-modeline](https://github.com/seagle0128/doom-modeline), and I am not 100% sure it is not a problem with that instead.

**Comment by wyuenho** [comment]
See #245

**Comment by dadinn** [comment]
I assume this means that the response on the [referenced issue](https://github.com/seagle0128/doom-modeline/issues/619) to increase doom-modeline height is not the right long-term solution.
