### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by xueyouchao** [domtronn/all-the-icons.el#36]
When I install all-the-icons through emacs package manager, I got the following error:
package 'font-lock+-0' is unavailable.

What does this mean?

**Comment by domtronn** [comment]
Are you using Melpa Stable or standard Melpa as your package repository?

`font-lock-+` isn't available in Melpa Stable, _(see Issue #32)_

**Comment by xueyouchao** [comment]
Thank you so much, yeap, I got it installed from Melpa unstable and it works, close the issue.
