### ISSUE TITLE
all icons broken after update.

### ISSUE THREAD

**Issue by mooseyboots** [domtronn/all-the-icons.el#365]
i recently updated all-the-icons.el via straight.el, and now display of most icons is broken.

i have either tofu (occasionally, eg for a modified file or .gz file), or more likely, the wrong icons display. in the modeline i see hotel bed, airplane passenger, and similar icons, where an appropriate icon to the file/buffer type should display.

i tried the troubleshooting as per the readme. i called `all-the-icons-install-fonts`, which i think fixed some icons in dired but not the modeline. calling `all-the-icons-insert-icons-for` on the different sets, and they work correctly for those given in the readme.

are there any further steps i might try out to fix this?

**Comment by mohkale** [comment]
This could be related to the recent nerd-icons v3 release that moved a bunch of code points to not interfere with some asian character sets. That said I'd be surprised if it impacted all-the-icons given it ships its own icon sets :thinking:.

**Comment by PoisonedPigeons** [comment]
I've been able to get icons back in some places by running `M-x nerd-icons-install-fonts`. The following command downloads and installs the nerd-icons font for the current user. Afterwards, for me at least, icons show up on [doom-modeline](https://github.com/seagle0128/doom-modeline) but not yet on [emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard).

**Comment by mooseyboots** [comment]
`nerd-icons-install-fonts` fixed it for me. perhaps worth adding to the docs as a thing to try when struff breaks?

**Comment by PoisonedPigeons** [comment]
@mohkale I think you are right when you say that this isn't an all-the-icons problem. I created [a minimal Emacs config](https://gist.github.com/PoisonedPigeons/dfb8470f59dc85af26b27390bfaf9ee4) with "only" all-the-icons[^1] and all icons seem to show up when I do `M-x all-the-icons-insert`. Then I added [doom-modeline](https://github.com/seagle0128/doom-modeline) to my testing configuration and indeed the icons didn't display properly. I was too eager to help out and didn't test things properly before making my first comment and for that I sincerely apologize. Maybe, we could report this issue to the developers of [doom-modeline](https://github.com/seagle0128/doom-modeline) and [emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard)?

[^1]: The only other package is included in the minimal config was use-package.

**Comment by yubing24** [comment]
This happens to me as well.

In my configuration, I have this in the early steps:
```el
(require 'package)

(setq package-native-compile t)
(setq load-prefer-newer t) 

(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
```
Here is my configuration for `all-the-icons`:
```el
(use-package all-the-icons
  :ensure t
  :pin melpa-stable
  :if (display-graphic-p)
  :diminish)
(use-package all-the-icons-dired
  :ensure t
  :pin melpa-stable
  :diminish
  :hook (dired-mode . all-the-icons-dired-mode))
(use-package all-the-icons-completion)
```

When I start my Emacs, sometimes it will pop-up a prompt asking if I want to update my packages, and I selected "yes".

Once the packages were updated, icons were broken, and were rendered as a square with four 0s and 1s in it.

The solution for me was to install the nerd icon like @mooseyboots mentioned. Neither `fs-cache -f -v` nor `all-the-icons-install-fonts` helped.

This happens on both my Fedora Linux and macOS.

**Comment by mohkale** [comment]
For future reference anyone else that encounters this issue please run `M-: (require 'nerd-icons)` before anything else. If this does not fail then you were already using nerd icons, it broke due to a regression in a new release, and updating the package will fix it. Please don't continue commenting here for issues you're encountering in another package.

**Comment by wyuenho** [comment]
Thank you @mohkale :) You've been a great help
