### ISSUE TITLE
svg branch notes

### ISSUE THREAD

**Issue by progfolio** [domtronn/all-the-icons.el#367]
I tried the svg branch out as requested here:

https://www.reddit.com/r/emacs/comments/14c5u1w/alltheicons_svg_beta/

A few notes:

- The command `all-the-icons-insert` is no longer autoloaded.
- Once I loaded the package, I notice the command hits the CPU pretty hard each time it is invoked. I ran the cpu profiler and it returns the following report (sorted by cpu time):

```
        3312  36%   Automatic GC
        1365  14% + all-the-icons-fluentui-system-icons
         996  10% + all-the-icons-material-icons
         679   7% + locate-library
         454   4% + find-auto-coding
         300   3% + #<compiled 0xce4f27cc2a345cb>
         218   2% + all-the-icons-fontawesome-4
         217   2% + all-the-icons-file-icons
         189   2% + assoc-default
         185   2% + all-the-icons--normalize-svg-doc
         160   1% + svg-print
         154   1% + #<compiled 0x84b3455eb51783e>
         152   1% + svg-image
         119   1% + all-the-icons-octicons
          99   1% + all-the-icons--resolve-icon-file-name
          91   0% + all-the-icons-vscode-codicons
          58   0% + #<compiled -0x1c8bf0213e73fc67>
          53   0% + all-the-icons--load-svg
          46   0% + #<compiled -0x1c8bf025b9cd9e67>
          46   0% + all-the-icons-devopicons
          35   0% + completing-read-default
          29   0% + set-auto-coding
          27   0% + read-extended-command-1
          18   0% + create-image
          18   0% + recursive-edit
          13   0% + seq-filter
          11   0% + all-the-icons-mfixx
          10   0% + kill-buffer
          10   0% + all-the-icons--parse-number
          10   0% + apply
           7   0% + get-device-terminal
           7   0% + complete-with-action
           6   0% + assq-delete-all
           6   0% + filtered-frame-list
           4   0% + framep-on-display
           4   0% + replace-buffer-in-windows
           4   0% + debug
           3   0% + all-the-icons--read-candidates-for-icon-set
           3   0% + frames-on-display-list
           3   0% + #<compiled 0x91afed28a490c16>
           3   0% + find-new-buffer-file-coding-system
           3   0% + all-the-icons--fluentui-system-icons-path
           3   0% + window-default-font-height
           3   0% + dom-set-attribute
           3   0% + #<compiled 0x89780afb8bae>
           3   0% + after-insert-file-set-coding
           3   0% + unrecord-window-buffer
           3   0% + image-compute-scaling-factor
           3   0% + #<compiled -0x1c8bf03b15d79667>
           3   0% + use-region-p
           3   0% + funcall-interactively
           2   0% + syntax-ppss
```

Possible that generating the candidates is putting some pressure on the GC?

- The icons were not displayed in the completion candidate strings (but inserted fine):

![image](https://github.com/domtronn/all-the-icons.el/assets/44036031/769287a6-ee15-40b8-b29e-0638cbee8870)

- It should be noted, too, that the svgs will not scale with `text-scale-adjust` functions.

The above was tested via Elpaca:

```emacs-lisp
(elpaca-test
  :dir "elpaca.ati-svg"
  :init
  (elpaca (all-the-icons :branch "svg" :files (:defaults "svg"))))
```

On GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-06-15

**Comment by wyuenho** [comment]
> The command all-the-icons-insert is no longer autoloaded.

Yes, it never should have been autoloaded in the first place as there no way to provide the optional params with the prefix.

> I notice the command hits the CPU pretty hard each time it is invoked.

Yes as the candidate list is huge. Improving performance on these insert functions is fairly low on the list of priorities as these are just debugging functions. Trying adjusting `gc-cons-threshold` and see if it makes a difference with Emacs' ancient garbage collector.

> It should be noted, too, that the svgs will not scale with text-scale-adjust functions.

That's a good point, do you have any suggestions?

> The icons were not displayed in the completion candidate strings (but inserted fine)

I can't reproduce this on Emacs 29 on macOS. Is this a bug in master?

**Comment by wyuenho** [comment]
Ok I've put the autoload back on `all-the-icons-insert`.
