### ISSUE TITLE
[SVG] All the alists are not availables

### ISSUE THREAD

**Issue by thierryvolpiatto** [domtronn/all-the-icons.el#370]
For my helm-all-the-icons package that allows showing all the icons available, now many are missing because some alists are empty:

```
(defvar helm-all-the-icons-alist '((all-the-icons-data-alltheicons-alist . all-the-icons-alltheicon)
                                   (all-the-icons-data-fa-icon-alist . all-the-icons-faicon)
                                   (all-the-icons-data-file-icon-alist . all-the-icons-fileicon)
                                   (all-the-icons-data-octicons-alist . all-the-icons-octicon)
                                   (all-the-icons-data-material-icons-alist . all-the-icons-material)
                                   (all-the-icons-data-weather-icons-alist . all-the-icons-wicon)))
```
Now only three alists are available whereas in master all are available.
For reference: https://github.com/emacs-helm/helm-all-the-icons

**Comment by wyuenho** [comment]
You are reaching directly into undocumented alist variables instead of the public `all-the-icons-[icon set]-data` functions.

You need to rewrite `helm-all-the-icons-sources`. Take a look at [this](https://github.com/domtronn/all-the-icons.el/blob/svg/all-the-icons.el#L111-L129) and [this](https://github.com/domtronn/all-the-icons.el/blob/svg/all-the-icons.el#L67-L75).

**Comment by thierryvolpiatto** [comment]
Jimmy Yuen Ho Wong ***@***.***> writes:

> You are reaching directly into undocumented alist variables instead of the public all-the-icons-[icon set]-data functions.
>
> You need to rewrite helm-all-the-icons-sources. Take a look at this and this.

Ah! ok, I will look at this as soon as possible.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Jimmy Yuen Ho Wong ***@***.***> writes:

> You need to rewrite helm-all-the-icons-sources.

Ok, done. Unfortunately you have removed `all-the-icons-font-families`
so now I have to hardcode it, could you provide it again?

Thanks.

>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by wyuenho** [comment]
There's `all-the-icons-sets` :)

**Comment by thierryvolpiatto** [comment]
Jimmy Yuen Ho Wong ***@***.***> writes:

> There's all-the-icons-sets :)

Great thanks, maybe add a defvaralias would be nice?

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by wyuenho** [comment]
@thierryvolpiatto 47e0cb99f2ebf11f4c8e6d9ab32e2be695bf3aaf

**Comment by thierryvolpiatto** [comment]
Thanks.
