### ISSUE TITLE
[SVG] Storage of svg files

### ISSUE THREAD

**Issue by thierryvolpiatto** [domtronn/all-the-icons.el#371]
Hello,
as notified before, having the directory containing svg files in the same directory containing lisp files cause problems when installing all-the-icons in /emacs/site-lisp.
I was wondering were files should be stored, ~/.local/share?
Also bundling the package with the svg files may make the installation process very long, what about having a command to fetch files from remote once the lisp files are installed by package.el?

**Comment by wyuenho** [comment]
I'm not sure I follow. What problem does it cause when all-the-icons is installed in site-lisp?

**Comment by thierryvolpiatto** [comment]
Jimmy Yuen Ho Wong ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> I'm not sure I follow. What problem does it cause when all-the-icons is installed in site-lisp?

Emacs takes ages to load. I guess it is because this directory contains
a .subdirs.el file, so all the subdirs of all-the-icons are added to load-path.


-- 
Thierry

**Comment by wyuenho** [comment]
Does 630514302271aadd0ac4054ff5548d15ed285209 work?

**Comment by thierryvolpiatto** [comment]
Jimmy Yuen Ho Wong ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Does 6305143 work?

Didn't try but yes, the .nosearch trick should work of course.
I was thinking of something different to fix this issue, I am actually
installing with a make file that install *.el and *.elc files in my lisp
directory and /svg in a directory used for data, here
~/share/all-the-icons/ (I modified source for this, see
https://github.com/thierryvolpiatto/all-the-icons.el/commit/5ab7c0e83e35d708acf9b28755fc4f608bd3f1a9).
Master branch is installing fonts/ in .local/share (aka $XDG_DATA_HOME) isn't it, why not
doing the same?
 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by wyuenho** [comment]
Because I don't want to introduce any installation step. Package data belongs with the package. They are immutable and not databases generated at runtime, there's no reason to put them anywhere else.

**Comment by thierryvolpiatto** [comment]
Jimmy Yuen Ho Wong ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Because I don't want to introduce any installation step. Package data
> belongs with the package. They are immutable and not databases
> generated at runtime, there's no reason to put them anywhere else.

Problem is at each update of the package people will have to pull a
bunch of svg files for no reasons.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by wyuenho** [comment]
Sounds just like any other package where only a couple of few files were updated in a release :)

**Comment by wyuenho** [comment]
I'm closing this. Let me know if this fails fix the perf problem when installing under site-lisp
