### ISSUE TITLE
odin-mode is void

### ISSUE THREAD

**Issue by jinzhongjia** [domtronn/all-the-icons.el#376]
I recently started experimenting with emacs, then after I install all-the-icons via elpaca, use-package reports me "symbol's function definition is void: odin-mode", it should be because of [this](https://github.com/domtronn/all-the-icons.el/blob/92d5ecc60a9bf145ea44d4304ba99f827848fe6e/all-the-icons.el#L764)

My emacs version is 29.1

I temporarily define odin-mode as an empty function to solve this problem. Is there any other way?

**Comment by wyuenho** [comment]
This should be fixed in 92d5ecc60a9bf145ea44d4304ba99f827848fe6e. Just reinstall all-the-icons again and you should be fine. Apologies.
