### ISSUE TITLE
Question regarding usage of icons for other places in Emacs

### ISSUE THREAD

**Issue by asok** [domtronn/all-the-icons.el#38]
Hi,
I love your package.

Have you ever thought about adding the icons to the buffer switcher or find file? At least for the buffer switching having the same icon for the buffers having the same major-mode would be a huge visual hint. I mean something like what you do with displaying the icon next to the icon name in `all-the-icons-insert`.

Do you think it's doable? Do you think that it would add a lot of overhead?

**Comment by domtronn** [comment]
Thanks for the kind words!

And nope, I haven't, my main focus was originally Neotree and the mode line, but I really like this idea!

It's definitely possible to do this. I personally use [Ivy](https://github.com/abo-abo/swiper) for my completion framework, and there's a lovely package called [Ivy Rich](https://github.com/yevgnen/ivy-rich) which shows more information when switching buffers and could definitely look at adding icons into it.

_w.r.t._ the overhead... It's mainly the amount of rendering/propertizing required... I can't see there being many issues if Neotree works okay? And I've only heard of performance issues on Windows.

I'm definitely gonna look into this myself but if you find anything do let me know 😄

**Comment by asok** [comment]
I also use ivy.

I came up with something like this:
```el
(defun all-the-icons-ivy--buffer-propertize (b s)
  (if (and (buffer-file-name b)
           (buffer-modified-p b))
      (propertize s 'face 'ivy-modified-buffer)
    s))

(defun all-the-icons-ivy--buffer-candidate (b s)
  (let* ((mode (buffer-local-value 'major-mode b))
         (icon (all-the-icons-icon-for-mode mode)))
    (format "%s\t%s"
            (if (symbolp icon) "\t" icon)
            (all-the-icons-ivy--buffer-propertize b s))))

(defun all-the-icons-ivy--file-candidate (s)
  (format "%s\t%s" (all-the-icons-icon-for-file s) s))

(defun all-the-icons-ivy-switch-buffer-transformer (s)
  (let ((b (get-buffer s)))
    (if b
        (all-the-icons-ivy--buffer-candidate b s)
      (all-the-icons-ivy--file-candidate s))))

(ivy-set-display-transformer 'ivy-switch-buffer 'all-the-icons-ivy-switch-buffer-transformer)
```

The only issue I have with it is that the icon for the current selection is being changed. It's either smaller which is fine, or for example in case of emacs-lisp-mode it's a completely different icon. Like here `all-the-icons.el` has got the correct icon, but for the currently selected `all-the-icons-scratch.el` it something else. Once you move the selection to something else the icon is back to the correct one.
<img width="265" alt="screen shot 2017-02-18 at 22 40 33" src="https://cloud.githubusercontent.com/assets/120457/23097156/62581664-f62d-11e6-9d9f-87d1aff37cc2.png">

Any idea what might be causing this?

**Comment by domtronn** [comment]
It's because Ivy's using a different face for the highlight text which is overriding the font family for the icon. However, there's a nice trick you can use with `propertize` and `font-lock+` which stops this from happening.

You basically set the `'display` property of a whitespace character to be the propertized icon, _(for example, see [here](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L590))_ so what you can do is;

```el
(defun all-the-icons-ivy--buffer-candidate (b s)
  (let* ((mode (buffer-local-value 'major-mode b))
         (icon (all-the-icons-icon-for-mode mode)))
    (format "%s\t%s"
            (propertize "\t" 'display (unless (symbolp icon) icon))
            (all-the-icons-ivy--buffer-propertize b s))))
```

Which will display the tab character either as the icon or a tab character if the icon doesn't exit.

**Comment by asok** [comment]
Thanks, now it works really well.

Now there's one thing left `all-the-icons-icon-for-mode` uses `all-the-icons-mode-icon-alist` which is pretty short. Maybe I could make a PR that extends the list with the data from `all-the-icons-icon-alist`. Or even better put the major-mode info to `all-the-icons-icon-alist` and change the way it is accessed. What do you think?

**Comment by domtronn** [comment]
The `mode-icon-alist` is more for anonymous buffers that don't have a file associated with them to match against the file alist, so things like `*scratch*` and `*Messages*`... The other use is for buffers that you _override_ the major mode for, for example, say I have a file called `foo.js`, it would match to `JavaScript` icon, but if I then call `(emacs-lisp-mode)`, it would override it to be the `Elisp` icon.

For the most part you should be able to use the `all-the-icons-icon-for-file` and then revert to using the `all-the-icons-icon-for-mode` but I'm more than happy to add more modes to the `mode-alist` 😄 I just think trying to add that as more meta data to the `icon-alist` will make the selection logic even more complex and verbose

**Comment by asok** [comment]
Just to let you know I've finally published the package - https://melpa.org/#/all-the-icons-ivy
