### ISSUE TITLE
Bottom bar.

### ISSUE THREAD

**Issue by AnthonyJacob** [domtronn/all-the-icons.el#39]
How did you get that nice bottom bar?

**Comment by domtronn** [comment]
I think you mean the mode line, in which case see #2, and also there's a [wiki page](https://github.com/domtronn/all-the-icons.el/wiki/Mode-Line) with code snippets that should work for this.

Also, I'm still fiddling with this in my own custom Emacs, and could have a play [with this snippet](https://github.com/domtronn/emacs/blob/master/init/spaceline-custom.el) although this is a little experimental 😅
