### ISSUE TITLE
[SVG] Icons increase the line height

### ISSUE THREAD

**Issue by Stebalien** [domtronn/all-the-icons.el#392]
First discussed in https://github.com/domtronn/all-the-icons.el/pull/391.

This is what icons look like in the `svg` branch.

![c-1](https://github.com/user-attachments/assets/066fd29a-546f-471a-8785-e3c07e81b38b)

This is what they look like if I change the size from the font "height" to the font "size":

![c-2](https://github.com/user-attachments/assets/8369f6d3-3830-4f6b-9457-2b2431645e13)

Notice that the lines in the second screenshot are closer together (i.e., don't have extra spacing).

I guess, the first question is: am I the only one with this issue? Maybe it's related to my build params? Specifically:

- Emacs 31 (built from master).
- Built with no toolkit (`--with-x-toolkit=no`).
- Built with cairo (`--with-cairo-xcb`) and no xft (`--without-xft`).

Making the following change to the `svg` branch fixes this for me:

```diff
diff --git a/all-the-icons.el b/all-the-icons.el
index 481a59e9a..a717f2ce4 100644
--- a/all-the-icons.el
+++ b/all-the-icons.el
@@ -1190,7 +1190,7 @@ cl-defmacro all-the-icons-define-icon
      (defun ,(all-the-icons--function-name name) (icon-name &rest args)
        (let* ((file-name (all-the-icons--resolve-icon-file-name icon-name ,alist (quote ,name))) ;; remap icons
               (face (or (and all-the-icons-color-icons (plist-get args :face)) 'all-the-icons-default))
-              (size (or (plist-get args :size) (aref (font-info (face-font face)) 3))) ;; font height = pixel-size + ascent + descent
+              (size (or (plist-get args :size) (aref (font-info (face-font face)) 2))) ;; font size
               (lib-dir (concat all-the-icons--lib-dir ,(format "svg/%s/" name)))
               (image-path (concat lib-dir ,(or (and svg-path-finder
                                                     `(apply ,svg-path-finder file-name lib-dir size args))
```

So I guess the first question is: can others reproduce this? Specifically, the line spacing issue?

**Comment by wyuenho** [comment]
Which Linux distro and/or Emacs GUI port are you on? I'm using the Emacs 29 NS Port on the macOS and I don't have this issue at all.

**Comment by Stebalien** [comment]
I'm using Arch Linux but I'm building Emacs from scratch:

```
 'configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var
 --mandir=/usr/share/man --with-gameuser=:games --with-modules --without-m17n-flt --without-selinux
 --without-pop --without-gconf --disable-gc-mark-trace --enable-link-time-optimization
 --with-native-compilation=yes --with-xinput2 --with-x-toolkit=no --without-toolkit-scroll-bars
 --without-xft --without-xaw3d --without-gsettings --with-cairo-xcb --with-sound=no
 --with-tree-sitter --without-gpm --without-compress-install
```

**Comment by wyuenho** [comment]
What are the `system-configuration-features` and `system-configuration-options` values?

**Comment by Stebalien** [comment]
Features:

> ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS HARFBUZZ JPEG LCMS2 LIBOTF LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY OLDXMENU PDUMPER PNG RSVG SECCOMP SQLITE3 THREADS TIFF TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM ZLIB

Options:

```
--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-modules --without-m17n-flt --without-selinux --without-pop --without-gconf --disable-gc-mark-trace --enable-link-time-optimization --with-native-compilation=yes --with-xinput2 --with-x-toolkit=no --without-toolkit-scroll-bars --without-xft --without-xaw3d --without-gsettings --with-cairo-xcb --with-sound=no --with-tree-sitter --without-gpm --without-compress-install '--program-transform-name=s/\\([ec]tags\\)/\\1.emacs/' 'CFLAGS=-march=native -mtune=native -O3 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fomit-frame-pointer -fno-math-errno -fno-trapping-math -fno-math-errno -fno-trapping-math -flto=auto' 'LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto'
```

(what I just posted, plus some build flags)

**Comment by Stebalien** [comment]
I can test with different font rendering backends and different toolkits over the weekend.

**Comment by wyuenho** [comment]
LOL, I don't even know what this configuration is, is this the GTK port? You haven't set --with-rsvg and yet Emacs's picked it up, and using Emacs 31, not even the Emacs 30 branch. If you can't reproduce this on Emacs 29 using one of the conventional port build I'm afraid you are on your own. If you can reprod this on Emacs 29 on one of the conventional ports, it's a bug in your Emacs port. Either case I can't help you.

Good luck.

**Comment by Stebalien** [comment]
Well, that's a rather unkind response. Please assume that I know what I'm doing and am not some idiot poking around in the dark, I've been doing this for a while now.

- It's not a "port", I'm building directly from unmodified Emacs source code. I'm avoiding GTK because it has known bugs when used with X11 and the maintainers have even discussed changing the default toolkit. But I will definitely check against GTK and report any bugs upstream if there's a difference.
- I've been experiencing this issue for quite a while now, it's not some fresh bug in Emacs 31.
- Harfbuzz does font shaping, Cairo does drawing. This is the [default config](https://gitlab.archlinux.org/archlinux/packaging/packages/emacs/-/blob/b2e187cbda98acfe01f46b299071978f86089006/PKGBUILD#L70-72) for Arch Linux and is generally the recommended config if you want things like ligatures to work.

**Comment by Stebalien** [comment]
I can reproduce the same issue with GTK:

```
In GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2) of
 2024-10-11 built on Laptop
Repository revision: e631a3f30679d3c4e465a5765e261b068e9357dc
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12101013
System Description: Arch Linux

Configured using:
 'configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var
 --mandir=/usr/share/man --with-gameuser=:games --with-modules --without-m17n-flt --without-selinux
 --without-pop --without-gconf --disable-gc-mark-trace --enable-link-time-optimization
 --with-native-compilation=yes --with-xinput2 --with-x-toolkit=gtk3 --without-xaw3d --with-cairo-xcb
 --with-sound=no --with-tree-sitter --without-gpm --without-compress-install
 '--program-transform-name=s/\([ec]tags\)/\1.emacs/' 'CFLAGS=-march=native -mtune=native -O3 -pipe
 -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security
 -fstack-clash-protection -fcf-protection -fomit-frame-pointer -fno-math-errno -fno-trapping-math
 -fno-math-errno -fno-trapping-math -flto=auto' 'LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed
 -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto''
```

> ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG LCMS2 LIBOTF LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

I will also try reproducing with Emacs 30, although that's not likely to make a difference. This sounds like a difference in how MacOS and Linux render fonts. Or maybe related to Cairo, Harfbuzz, etc. I'm not sure what your build config looks like.

**Comment by wyuenho** [comment]
This is my `system-configuration-features`

`"ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XWIDGETS ZLIB"`

And my `system-configuration-options`

`"--prefix=/opt/local --disable-silent-rules --without-dbus --without-gconf --without-libotf --without-m17n-flt --with-libgmp --with-gnutls --with-json --with-xml2 --with-modules --with-sqlite3 --with-webp --infodir /opt/local/share/info/emacs --with-ns --with-lcms2 --without-harfbuzz --without-imagemagick --without-xaw3d --with-rsvg --with-xwidgets --with-native-compilation=aot --with-tree-sitter 'CFLAGS=-pipe -Os -Wno-attributes -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64' 'CPPFLAGS=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-no_pie -Wl,-rpath  /opt/local/lib/gcc14 -Wl,-rpath /opt/local/lib -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64'"`

By "port", I mean one of the 7 `window-system` s built into Emacs since eternity. "Port" is Emacs lingo for one of these GUI frontends. Apparently most people use the `pgtk`, `w32`, `ns` or the forked `mac` ports. Your build has no x-toolkit or xft, if you are going to go bleeding edge, expect to bleed.

In any case, this is a bug in the port and you should report the bug to emacs-dev. FYI, this is a screenshot from the ns port:

<img width="411" alt="Screenshot 2024-10-11 at 8 06 08 PM" src="https://github.com/user-attachments/assets/3f92446b-356e-4708-b472-00f70b0b9536">

**Comment by Stebalien** [comment]
> "Port" is Emacs lingo for one of these GUI frontends.

"Port" means programs ported to system X (it comes from the days when programs to various unix flavors). Although you appear to be right in this case as X11 is considered a "port" from the original TTY version.

> Your build has no x-toolkit or xft, if you are going to go bleeding edge, expect to bleed.

As commented above, I've re-tested with GTK and it has the same issue. Also... no-x-toolkit is hardly "bleeding edge", it's about as non-bleeding edge as you can get.

XFT is the old font shaping library, harfbuzz is the new one. If you compile with XFT, you get the following warning:

> This configuration uses libXft, which has a number of
    font rendering issues, and is being considered for removal in the
    next release of Emacs.  Please consider using Cairo graphics +
    HarfBuzz text shaping instead (they are auto-detected if the
    relevant development headers are installed).

That warning was added in 2020. Even Debian stable uses harfbuzz+cairo (see https://packages.debian.org/bookworm/emacs-gtk).

---

But at the end of the day, this does indeed look like a rendering difference between our two builds, possibly related to harfbuzz but I'd have to test with xft to be sure. My guess is that it's simply an NS quirk.

**Comment by c256** [comment]
Background:
FWIW, emacs uses "port" internally to describe its support for both various
operating systems and UI systems (toolkits), for decades. The default
toolkit has been gtk for many years. Xft was supplanted as the default for
Cairo+Harfbuzz several years ago, and will continue to be supported for
legacy systems, because it is strictly worse in features and support.

There is periodic discussion about updating the default toolkit support
from gtk, and pgtk is popular, but also less stable than gtk and missing
some features (due to core wayland design issues). To the best of
emacs-devel's knowledge, gtk (the default) is the most popular installed
base. macOS support is popular but somewhat split between the ns and mac
ports, and remains somewhat unstable to this day (if anyone reading this is
interested in emacs and is comfortable with Cocoa/NS/OpenStep, emacs could
really use help in that area. (In practice, many people end up using the
carbon support (aka "mac port"), despite it being deprecated by Apple a
long time ago, because in practice it continues to be functional (owing no
doubt to its strong presence in iOS). GNU Emacs, in practice, currently
prefers the ns port for a few reasons, including that it supports the
free/libre OpenStep platform, and it's _theoretically_ more supported, but
GNU Emacs doesn't (anymore) have an ns port maintainer anywhere nearly so
dedicated/strong/etc as Mitsuharu Yamamoto.

For this case, please do report the problem as an emacs bug, especially if
you can find a simple reproduction case. Font/line height is bit of a dark
art, since different UI systems (mac, X11, wayland, windows, haiku, etc.)
do different things with the same numbers, entirely independent of emacs.

I hope that helps,
~Chad

**Comment by wyuenho** [comment]
I see. On [Macports](https://github.com/macports/macports-ports/blob/master/editors/emacs/Portfile) (not to be confused with the mac Emacs port, aka the Carbon port, neither the X11 nor the GTK port uses Cairo and Harfbuzz together. I guess the cardinality of the intersection of the people who use macOS, MacPorts, Emacs and GTK is tending towards 0 if not there already.

@Stebalien 
Give Emacs 29 and 30 a try, if the problem still persists, it's a bug for emacs-devel. For what it's worth, I think NS does the right thing. Any propertized strings with a display property shouldn't be considered text and therefore rendering should not pretend the image as text having any notion of ascent or descent, although the presence of the `:ascent`  property seems to contradict that.

@c256 Thanks for the FYI. I knew Harfbuzz was blessed a couple of years ago but I didn't know it replaced Xft. I always assume Emacs just works (or not work, depending on your perspective) everywhere on even MS-DOS :P

**Comment by wyuenho** [comment]
I'm temporarily reopening this issue in case this issue is proven to be prevalent in ports other than NS and on an RC or a stable Emacs version. In the event of such case, it should be trivial to select the default height according to different font rendering backends.

**Comment by Stebalien** [comment]
I've tested it on Emacs 29.4 with a standard package and can still reproduce it (also with `emacs -Q`, default config, default fonts, etc.). Build details as follows:

In GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2)
Windowing system distributor 'The X.Org Foundation', version 11.0.12101013
System Description: Arch Linux

Configured using:
 'configure --sysconfdir=/etc --prefix=/usr --libexecdir=/usr/lib --with-tree-sitter
 --localstatedir=/var --with-cairo --disable-build-details --with-harfbuzz --with-libsystemd
 --with-modules --with-x-toolkit=gtk3 'CFLAGS=-march=x86-64-v4 -O3 -pipe -fno-plt -fexceptions
 -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection
 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -mpclmul -g
 -ffile-prefix-map=/startdir/src=/usr/src/debug/emacs -flto=auto -falign-functions=32'
 'LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
 -Wl,-z,pack-relative-relocs -flto=auto -falign-functions=32''

Options:

```
--sysconfdir=/etc --prefix=/usr --libexecdir=/usr/lib --with-tree-sitter --localstatedir=/var --with-cairo --disable-build-details --with-harfbuzz --with-libsystemd --with-modules --with-x-toolkit=gtk3 'CFLAGS=-march=x86-64-v4 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -mpclmul -g -ffile-prefix-map=/startdir/src=/usr/src/debug/emacs -flto=auto -falign-functions=32' 'LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto -falign-functions=32'
```

Features:

```
ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB
```

**Comment by wyuenho** [comment]
Give 5d1dd18 a try

**Comment by Stebalien** [comment]
It works perfectly, thanks!

**Comment by wyuenho** [comment]
Thanks for the report!

**Comment by kyano** [comment]
![image](https://github.com/user-attachments/assets/413f5c65-19e7-4eb7-9b9c-afdf00501cfd)

It's strange. For me, reverting commit 5d1dd18 does not cause any line height issues.
As you can see from the attached screenshot, commit 5d1dd18 makes the icons too small relative to the normal text size.

Here is my `system-configuration-features` and `system-configuration-options`:

> "ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ IMAGEMAGICK JPEG LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM GTK3 ZLIB"

> "--prefix=/usr/local/emacs-31 --enable-locallisppath=/usr/share/emacs/site-lisp --enable-link-time-optimization --with-mailutils --with-sound=alsa --with-wide-int --with-xpm --with-jpeg --with-tiff --with-gif --with-png --with-rsvg --with-webp --with-sqlite3 --with-lcms2 --with-libsystemd --with-cairo --with-xml2 --with-imagemagick --with-tree-sitter --with-harfbuzz --with-libotf --with-pgtk --with-dbus --with-gsettings --with-gnutls --with-zlib --with-modules --with-threads --with-file-notification=inotify --without-xwidgets --with-native-compilation --with-libgmp --disable-gc-mark-trace 'CFLAGS=-march=alderlake -mtune=alderlake -O2 -fomit-frame-pointer -pipe'"

I'm using self-built Emacs 31 (from the master branch), with pure-gtk(GTK3) on WSL.
I also use self-built Emacs 31 with NS for my work, and reverting the commit gave me the same experience.

**Comment by kyano** [comment]
> This commit (https://github.com/domtronn/all-the-icons.el/commit/5d1dd180783419a5e6c8966f36d4f06264487819) shouldn't have any effect on NS.

I mean, "It looks the same after reverting the commit **on my WSL env.**" (if the author uses NS as the reference env.)

I will try to reproduce it without pgtk after I leave work. (I live in KST timezone)
Anyway, did you try pgtk build to reproduce this when this was issued? I do not know whether there've been any changes in emacs upstream or not, after Oct.

**Comment by Stebalien** [comment]
Oh, I see. I also missed the WSL part, that might be related although, IIRC, WSL is basically just a VM with some special sauce now so it shouldn't be related.

> Anyway, did you try to use pgtk build to reproduce this when this was issued? I do not know whether there've been any changes in emacs upstream or not, after Oct.

No, I use Emacs on X so I tested with no toolkit and with gtk3 (X), but not pure gtk.

**Comment by kyano** [comment]
🤔 Sadly, I can NOT reproduce the line height issue.
![image](https://github.com/user-attachments/assets/8b73daea-f8f7-4177-8c5c-aadfb9ca8c48)

Here is my X11 build info:
> "ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ IMAGEMAGICK JPEG LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB"

> "--prefix=/usr/local/emacs-31-x11 --enable-locallisppath=/usr/share/emacs/site-lisp --enable-link-time-optimization --with-mailutils --with-sound=alsa --with-wide-int --with-xpm --with-jpeg --with-tiff --with-gif --with-png --with-rsvg --with-webp --with-sqlite3 --with-lcms2 --with-libsystemd --with-cairo --with-xml2 --with-imagemagick --with-tree-sitter --with-harfbuzz --with-libotf --without-pgtk --with-x --with-dbus --with-gsettings --with-gnutls --with-zlib --with-modules --with-threads --with-file-notification=inotify --without-xwidgets --with-native-compilation --with-libgmp --disable-gc-mark-trace 'CFLAGS=-march=alderlake -mtune=alderlake -O2 -fomit-frame-pointer -pipe'"

<details>
<summary>This is my configure script to build pure-gtk:</summary>

```sh
#!/bin/bash

CFLAGS="-march=alderlake -mtune=alderlake -O2 -fomit-frame-pointer -pipe" \
      ./configure \
      --prefix=/usr/local/emacs-31 \
      --enable-locallisppath=/usr/share/emacs/site-lisp \
      --enable-link-time-optimization \
      --with-mailutils \
      --with-sound=alsa \
      --with-wide-int \
      --with-xpm \
      --with-jpeg \
      --with-tiff \
      --with-gif \
      --with-png \
      --with-rsvg \
      --with-webp \
      --with-sqlite3 \
      --with-lcms2 \
      --with-libsystemd \
      --with-cairo \
      --with-xml2 \
      --with-imagemagick \
      --with-tree-sitter \
      --with-harfbuzz \
      --with-libotf \
      --with-pgtk \
      --with-dbus \
      --with-gsettings \
      --with-gnutls \
      --with-zlib \
      --with-modules \
      --with-threads \
      --with-file-notification=inotify \
      --without-xwidgets \
      --with-native-compilation \
      --with-libgmp \
      --disable-gc-mark-trace
```
</details>

<details>
<summary>And this is the diff for building X11:</summary>

```diff
--- configure_local     2024-12-14 04:58:37.288338324 +0900
+++ configure_x11       2024-12-18 04:54:18.510376435 +0900
@@ -2,7 +2,7 @@

 CFLAGS="-march=alderlake -mtune=alderlake -O2 -fomit-frame-pointer -pipe" \
       ./configure \
-      --prefix=/usr/local/emacs-31 \
+      --prefix=/usr/local/emacs-31-x11 \
       --enable-locallisppath=/usr/share/emacs/site-lisp \
       --enable-link-time-optimization \
       --with-mailutils \
@@ -24,7 +24,8 @@ CFLAGS="-march=alderlake -mtune=alderlak
       --with-tree-sitter \
       --with-harfbuzz \
       --with-libotf \
-      --with-pgtk \
+      --without-pgtk \
+      --with-x \
       --with-dbus \
       --with-gsettings \
       --with-gnutls \
```
</details>

<details>
<summary>The config summary output of X11 is here:</summary>

```
Configured for 'x86_64-pc-linux-gnu'.

  Where should the build process find the source code?    .
  What compiler should emacs be built with?               gcc -march=alderlake -mtune=alderlake -O2 -fomit-frame-pointer -pipe -flto=20 -ffat-lto-objects
  Should Emacs use the GNU version of malloc?             no
    (The GNU allocators don't work with this system configuration.)
  Should Emacs use a relocating allocator for buffers?    no
  Should Emacs use mmap(2) for buffer allocation?         no
  What window system should Emacs use?                    x11
  What toolkit should Emacs use?                          GTK3
  Where do we find X Windows header files?                Standard dirs
  Where do we find X Windows libraries?                   Standard dirs
  Does Emacs use -lXaw3d?                                 no
  Is Emacs being built for Android?                       no
  Does Emacs use the X Double Buffer Extension?           yes
  Does Emacs use -lXpm?                                   yes
  Does Emacs use -ljpeg?                                  yes
  Does Emacs use -ltiff?                                  yes
  Does Emacs use a gif library?                           yes -lgif
  Does Emacs use a png library?                           yes -lpng16
  Does Emacs use -lrsvg-2?                                yes
  Does Emacs use -lwebp?                                  yes
  Does Emacs use -lsqlite3?                               yes
  Does Emacs use cairo?                                   yes
  Does Emacs use -llcms2?                                 yes
  Does Emacs use imagemagick?                             yes
  Does Emacs use native APIs for images?                  no
  Does Emacs support sound?                               yes
  Does Emacs use -lgpm?                                   no
  Does Emacs use -ldbus?                                  yes
  Does Emacs use -lgconf?                                 no
  Does Emacs use GSettings?                               yes
  Does Emacs use a file notification library?             yes (inotify)
  Does Emacs use access control lists?                    yes -lacl -lattr
  Does Emacs use -lselinux?                               yes
  Does Emacs use -lgnutls?                                yes
  Does Emacs use -lxml2?                                  yes
  Does Emacs use -lfreetype?                              yes
  Does Emacs use HarfBuzz?                                yes
  Does Emacs use -lm17n-flt?                              no
  Does Emacs use -lotf?                                   yes
  Does Emacs use -lxft?                                   no
  Does Emacs use -lsystemd?                               yes
  Does Emacs use -ltree-sitter?                           yes
  Does Emacs use the GMP library?                         yes
  Does Emacs directly use zlib?                           yes
  Does Emacs have dynamic modules support?                yes
  Does Emacs use toolkit scroll bars?                     yes
  Does Emacs support Xwidgets?                            no
  Does Emacs have threading support in lisp?              yes
  Does Emacs support the portable dumper?                 yes
  Does Emacs support legacy unexec dumping?               no
  Which dumping strategy does Emacs use?                  pdumper
  Does Emacs have native lisp compiler?                   yes
  Does Emacs use version 2 of the X Input Extension?      yes
  Does Emacs generate a smaller-size Japanese dictionary? no
```
</details>

**Comment by Stebalien** [comment]
Interesting... what font? I just reproduced it with `IBM Plex Mono`, `JetBrains Mono`, and `Source Code Pro`, but not `DejaVu Sans Mono`.

Also, do you have any default `line-spacing` configured? It doesn't look like it, but I figured I'd check.

**Comment by wyuenho** [comment]
What's the return value of `font-info` for the fonts in question?

**Comment by kyano** [comment]
> Interesting... what font? I just reproduced it with IBM Plex Mono, JetBrains Mono, and Source Code Pro, but not DejaVu Sans Mono.

🫨 Oh, I'm using `IBM Plex Mono`.

**Comment by kyano** [comment]
![image](https://github.com/user-attachments/assets/55f3fc55-18d6-48aa-8305-74919fd4a468)

Maybe it's better than `(font-info)`:
```
             position: 1644 of 3217 (51%), column: 54
            character: ￼ (displayed as ￼) (codepoint 65532, #o177774, #xfffc)
              charset: unicode-bmp (Unicode Basic Multilingual Plane (U+0000..U+FFFF))
code point in charset: 0xFFFC
               syntax: w        which means: word
             category: .:Base
             to input: type "C-x 8 RET fffc" or "C-x 8 RET OBJECT REPLACEMENT CHARACTER"
          buffer code: #xEF #xBF #xBC
            file code: #xEF #xBF #xBC (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    ftcrhb:-GOOG-Noto Serif-medium-normal-normal-*-15-*-*-*-*-0-iso10646-1 (#x239)

Character code properties: customize what to show
  name: OBJECT REPLACEMENT CHARACTER
  general-category: So (Symbol, Other)
  decomposition: (65532) ('￼')
```

I think IBM Plex Mono does not have a glyph for 0xFFFC, so fontconfig chose Noto Serif instead. 🤔

**Comment by Stebalien** [comment]
My "unknown glyph" is displayed by Iosevka Fixed, but that _shouldn't_ matter as the character is replaced by the icon itself. Changing `￼` to `x` doesn't seem to change anything.

In terms of exact fonts, I tested with `IBMPlexMono-Regular.ttf` from https://github.com/IBM/plex/releases/tag/%40ibm%2Fplex-mono%401.1.0. The sha256 is `fe11304a5fe956d5744e9b6a246cc83d90425245e75a62230044966ca96a7f50`.

Are you using TTF or OTF?

**Comment by wyuenho** [comment]
On Emacs 29 0xFFFC is automatically replaced to a space for me

```
             position: 300 of 485 (62%), column: 1
            character: SPC (displayed as SPC) (codepoint 32, #o40, #x20)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x20
               script: latin
               syntax:   	which means: whitespace
             category: .:Base, a:ASCII, l:Latin
             to input: type "C-x 8 RET 20" or "C-x 8 RET SPACE"
          buffer code: #x20
            file code: #x20 (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    mac-ct:-*-JetBrains Mono NL-regular-normal-normal-*-12-*-*-*-m-0-iso10646-1 (#x378)

Character code properties: customize what to show
  name: SPACE
  general-category: Zs (Separator, Space)
  decomposition: (32) (' ')

There are 2 overlays here:
 From 299 to 365
  face                 hl-line
  priority             -50
  window               #<window 18 on *Files*>
 From 299 to 365
  face                 hl-line
  priority             -50
  window               nil


Note that character has an invisibility property,
  so the character displayed at point in the buffer may
  differ from the character described here.

There are text properties here:
  fontified            t
  invisible            dired-hide-details-detail

[back]

```

**Comment by kyano** [comment]
I'm using OTF, from the most recent one of master branch.

---

I use all-the-icons not only for dired, but also for some other fancy things like modeline, tab-bar header and welcome buffer.
And it looks better with `3` everywhere, without any line height issues, even on x11 build.

- Font height(3):
![image](https://github.com/user-attachments/assets/c80d68f4-c81c-40e1-ba52-3535138a5dff)

- Font size(2):
![image](https://github.com/user-attachments/assets/1dd5ccec-efdc-438a-8f10-d7cee7c11cbc)

**Comment by wyuenho** [comment]
@kyano If you replace the 0xFFFC at https://github.com/domtronn/all-the-icons.el/blob/svg/all-the-icons.el#L1219 to a space, does it work for you?

**Comment by kyano** [comment]
- the current:
![image](https://github.com/user-attachments/assets/677a0f3b-805e-46e4-a45c-1589f4b5be60)

- reverting the commit:
![image](https://github.com/user-attachments/assets/7f0fc971-1c5b-4c9e-8a3c-5396a02fb9af)

---

After replace 0xFFFC with a space, nothing changed.
Using font height makes the same result to NS.

**Comment by wyuenho** [comment]
Interesting. @Stebalien sounds like the problem is on your end man :)

**Comment by kyano** [comment]
Let me summarize what I issued:
I can not reproduce the OP's first issue, and the fix made another problem for me.

> the first question is: am I the only one with this issue? 

And then, am I the only one without the issue? 😭

**Comment by wyuenho** [comment]
Yes, but reverting will work for both of us. I'm waiting for OP's investigation.

**Comment by Stebalien** [comment]
I've tried the OTF version of the font and can still reproduce it.

> Interesting. @Stebalien sounds like the problem is on your end man :)

Sounds like it. I'll try testing in different environments when I get the chance (especially on Ubuntu) but like the best solution is to just revert this for now.

The interesting part is that it's clearly not some kind of float rounding issue, font-scaling scaling issue, etc. because the required height exactly matches the font "size" on my system

**Comment by wyuenho** [comment]
Alternatively, you can figure out some value that's different between the both of you that I can detect, and I can multiplex the aref around that.

**Comment by Stebalien** [comment]
The only consistent difference between all of us is the underlying OS: MacOS versus WSL versus Arch Linux.

@kyano just checking, that's WSL 2 right? What distribution?

**Comment by kyano** [comment]
I also checked the issue #391, and it seems that @Stebalien shared screenshots of only `vertico` (and it's related extensions to show icons?).

Could you please test simply like this?:
![image](https://github.com/user-attachments/assets/178a2154-670c-4a61-9654-7d7138efa1f6)

And JFYI: here's my own code for showing icons in treemacs/dired: https://github.com/kyano/treemacs-all-the-icons-svg.el/blob/master/treemacs-all-the-icons-svg.el
As you see, I do not touch anything related to font/icon size.

**Comment by kyano** [comment]
> @kyano just checking, that's WSL 2 right? What distribution?

Yes WSL2, and Debian sid.

**Comment by Stebalien** [comment]
I've been testing in a scratch buffer.

Without the patch (font height):

![without-patch](https://github.com/user-attachments/assets/bc8f2a27-c2f7-405e-bac7-dd67dc513221)

With the patch (font size):

![with-patch](https://github.com/user-attachments/assets/544af024-a3f3-483a-ae6d-3bfaab9fee57)

("bar" because the original test was 3 lines of foo/bar/baz...)

**Comment by kyano** [comment]
Did you call the all-the-icons provided method directly, like `all-the-icons-icon-for-dir`? 🤔 
So strange...

![image](https://github.com/user-attachments/assets/2f131c2f-3808-45a4-b81f-c27b9f8252df)

I thought a major difference is "how we call the icons", but it may not then.

**Comment by Stebalien** [comment]
I called `all-the-icons-insert` (interactively), then copy-pasted the line over and over.

But I've managed to isolate it: It's my X11 DPI setting (`Xft.dpi` in `Xresources`). Switching to a new user without my Xresources file fixes the issue, re-importing my Xresources file breaks it again. I assumed it wasn't related to font scaling the "pixel size" works perfectly, but it looks like the ratio of "font height" to "pixel size" is usually 3:2 (my DPI is 144 versus the standard 96).

So yeah, revert this for now. Setting the DPI is a common way to deal with HiDPI screens on X (without resorting to fractional scaling) but this fix is simply incorrect.

**Comment by Stebalien** [comment]
Actually... I don't think it has to do with DPI, I think it's font size. Even without setting the X DPI, increasing the font-size reproduces the issue in a completely fresh profile (fresh i3 instance with no X or Emacs config).

To reproduce, try running:

```elisp
(set-face-attribute 'default nil :height 200)
```

Then insert an icon.
