### ISSUE TITLE
Icons not work correctly (linux)

### ISSUE THREAD

**Issue by gangashman** [domtronn/all-the-icons.el#40]
I have strange symbols instead icons.
![screenshot_20170221_190501](https://cloud.githubusercontent.com/assets/7021713/23181480/35e9f358-f886-11e6-9747-273e3a71aa16.png)

I use all-the-icons trough use-package:
```
(use-package all-the-icons
  :ensure t)
```
I have all files from this repo, including tff files. Thanks for any help!

**Comment by zerodivisionfeature** [comment]
I'm guessing you want the icons to show up in neotree, got it working with this line on Linux and OSx

    (setq neo-theme (if (display-graphic-p) 'icons 'arrow))

**Comment by gangashman** [comment]
No, It didn't help. Icons doesn't work when I `use all-the-icons-insert`, not just in neotree.

**Comment by zerodivisionfeature** [comment]
oh, I see, have you tried with:

    (require 'all-the-icons)

works for me.

**Comment by domtronn** [comment]
Sorry for the late reply! I am looking into this, but it requires me to setup a Linux box in order to try and replicate this which I don't have easy access or time to do at the moment... 

I know you mentioned that the icons work when you run `all-the-icons-insert`, but could you try running 

```el
(all-the-icons-insert-icons-for 'octicon)
```

inside a `fundamental-mode` buffer and send me a photo of this? It's strange that this is only happening in `NeoTree`

**Comment by gangashman** [comment]
This work fine. Screenshot:
![screenshot_20170320_175017](https://cloud.githubusercontent.com/assets/7021713/24105399/cbfdeb78-0d95-11e7-91d4-73c5ccc317a9.png)

**Comment by domtronn** [comment]
That, to me, doesn't look like [Octicons](https://github.com/domtronn/all-the-icons.el/blob/master/fonts/octicons.ttf) is installed... If you put your cursor/caret in-front of the `arrow-down` symbol and then call `describe-char`, what output do you get?

This should tell you what font its using to display the character, the unicode code etc... Should help with debugging this issue!

**Comment by gangashman** [comment]
I have all .dff from repo, but my `octicons.ttf` was differnt.
![screenshot_20170320_184111](https://cloud.githubusercontent.com/assets/7021713/24107826/dceac3e6-0d9c-11e7-8f1c-c58bc01debef.png)

**Comment by domtronn** [comment]
So the display of the icon should use `github-octicons` font, _(see my screenshot for the `mac-ct:` property)_, whereas yours _(the `xft:` property)_ is using `PfEd-UnDotum` font?

Could you try reinstalling the `octicons` font?

<img width="1068" alt="screen shot 2017-03-20 at 15 53 58" src="https://cloud.githubusercontent.com/assets/5881414/24108519/bcc0d34c-0d85-11e7-8ee0-418958988898.png">

**Comment by gangashman** [comment]
I reinstall `octicons`, but all the same.

` xft:-PfEd-UnDotum-normal-normal-normal-*-26-*-*-*-*-0-iso10646-1 (#x4910)`

![screenshot_20170320_191618](https://cloud.githubusercontent.com/assets/7021713/24109471/ce702590-0da1-11e7-9c4f-e8ef6a1176fd.png)

**Comment by liaowang11** [comment]
Would u please do:
```shell
fc-match "github\-octicons"
```

**Comment by gangashman** [comment]
`fc-match "github\-octicons"` return: `DejaVuSans.ttf: "DejaVu Sans" "Book"`

**Comment by liaowang11** [comment]
How about
``` shell
fc-match -a 'github\-octicons' | grep octicons
```
Just need to make sure you have the font installed.

**Comment by mattiasb** [comment]
Since I just was bitten by this. Installation of the fonts is as simple as:
```shell
$ https://github.com/domtronn/all-the-icons.el.git
$ install -m 0644 -D all-the-icons.el/fonts/*.ttf -t ~/.local/share/fonts/
```

**Comment by gangashman** [comment]
Thanks, mattiasb! Its fix the problem!
