### ISSUE TITLE
Icon issue when creating a new js file

### ISSUE THREAD

**Issue by ztlevi** [domtronn/all-the-icons.el#43]
When I created a new js file, the icon looks like this. Interesting bug.
![](https://ww2.sinaimg.cn/large/006tNc79gy1fd6th9ofdvj30gj056gm4.jpg)

**Comment by domtronn** [comment]
That's the [Jasmine Icon](https://jasmine.github.io/) - Which is my personal favourite testing framework for JS so if you make a `test`/`spec` javascript file it will use that icon instead
