### ISSUE TITLE
Icon unicode conflict?

### ISSUE THREAD

**Issue by liaowang11** [domtronn/all-the-icons.el#46]
Using neotree `icons` theme, some icons are wrong.
Take a look at the screenshot: 
![selection_419](https://cloud.githubusercontent.com/assets/255802/23994963/56e5d30c-0a82-11e7-9ca2-526e6c5f612a.png)
I don't know why weather icons messed in.
```
             position: 1137 of 7154 (16%), column: 5
            character:  (displayed as ) (codepoint 61487, #o170057, #xf02f)
    preferred charset: unicode (Unicode (ISO10646))
code point in charset: 0xF02F
               syntax: w 	which means: word
             category: L:Left-to-right (strong)
             to input: type "C-x 8 RET f02f"
          buffer code: #xEF #x80 #xAF
            file code: #xEF #x80 #xAF (encoded by coding system utf-8)
              display: by this font (glyph code)
    xft:-UKWN-Weather Icons-normal-normal-normal-*-19-*-*-*-*-0-iso10646-1 (#x3F)
```

**Comment by domtronn** [comment]
Occasionally I see people who seem to have unicode character conflicts, this shouldn't happen since Emacs handles the font families... I'm not sure why this is happening?

Did you install the Icon fonts provided with this repo? Or directly from their sources?

I'll start investigating this though 😃

**Comment by liaowang11** [comment]
I reinstalled `octicons.ttf` and restart emacs, it's working again. Really weird.
Seems this time `octicons` takes precedence over `weather icons`.
Anyway closing this for now. Thanks for this cool package.
![image](https://cloud.githubusercontent.com/assets/255802/24098399/375b2e58-0da5-11e7-92c9-c833adbb98ce.png)

**Comment by stardiviner** [comment]
@liaowang11 How do you display the upper details info in Emacs?

**Comment by domtronn** [comment]
You can call `M-x describe-char` over a character
