### ISSUE TITLE
wiki `spaceline` example broken

### ISSUE THREAD

**Issue by idoo** [domtronn/all-the-icons.el#47]
With new spaceline I got
```
Error during redisplay: (eval (spaceline-ml-ati)) signaled (void-function spaceline-ml-ati)
```

**Comment by domtronn** [comment]
A lot of people seem to get this issue where the file doesn't actually declare the modeline... I'm not sure why it happens but including the `spacline-ml-ati.el` file should call [`(spaceline-compile "ati" ...)`](https://github.com/domtronn/emacs/blob/master/init/spaceline-custom.el#L529) which is a macro that should define `spaceline-ml-ati`.

If you go into your file and then evaluate the `spaceline-compile` line, is `spaceline-ml-ati` defined at that point?

**Comment by idoo** [comment]
@domtronn no, it's still not defined :(

**Comment by idoo** [comment]
Probably I found the reason https://github.com/jwiegley/use-package/issues/440
