### ISSUE TITLE
Show icons in Org-Agenda buffer

### ISSUE THREAD

**Issue by stardiviner** [domtronn/all-the-icons.el#55]
Org-Agenda can display icon in buffer with the following settings:

```elisp
(setq org-agenda-category-icon-alist
      '(("Diary" "~/.emacs.d/resources/icon/diary.xpm" nil nil :ascent center)
        ("Todo" "~/.emacs.d/resources/icon/todo.xpm" nil nil :ascent center)
        ("Star" "~/.emacs.d/resources/icon/star.xpm" nil nil :ascent center)
        ;; ("Org" "~/.emacs.d/resources/icon/Org-mode.xpm" nil nil :ascent center)
        ("Org" '(all-the-icons-faicon "cogs") nil nil :ascent center)
...
```

I tried the upper method, but it does not work. Hope to find a way to show all-the-icons in org-agenda buffer. Thanks.

**Comment by domtronn** [comment]
@stardiviner Could you post a screenshot of an `org-agenda` file which contains the XPM icons? Just as a frame of reference :) I just don't have the resources to see what this should look like...

And please don't accidentally post any data you're not happy sharing! 😅

**Comment by stardiviner** [comment]
![org-agenda icons](https://cloud.githubusercontent.com/assets/378699/25127385/2e524bbe-2468-11e7-917c-7286620f4771.png)

**Comment by domtronn** [comment]
I can't seem to get the icons to show up myself... I've downloaded your `todo.xpm` icon and set the `org-agenda-category-alist` variable to match it, but when I call `org-agenda` and press `t` to list all TODO entries, there are no icons there... 😞 

However, I _have_ looked into the `org-agenda` code on how it displays the icons... And I have some things you could try...

```el
(setq org-agenda-category-icon-alist
      `(("Org" ,(list (all-the-icons-faicon "cogs")) nil nil :ascent center)))
```

The code that gets the icon for an agenda type checks whether or not the `cadr` is a list, if _not_ it tries to create an XPM image. It then propertizes a space with the `'display` property of that icon.

Also, you need the backtick _(`)_ above to evaluate the function and get the propertized icon string as part of the setup...

This _should_ work, but please let me know the results 👍

**Comment by stardiviner** [comment]
Your code works. Thanks very much.
