### ISSUE TITLE
Problem with the face

### ISSUE THREAD

**Issue by sebastiencs** [domtronn/all-the-icons.el#59]
![peek 27-04-2017 18-01](https://cloud.githubusercontent.com/assets/5273820/25478767/fc4fc876-2b74-11e7-8f00-14e2f8d5c4b5.gif)

If I set the face once for an icon, I cannot get the orignal face with a second call.
Is it an expected behavior ?
I also tried with `:face 'default` but it returns a different icon.

**Comment by domtronn** [comment]
Ahh, yep! Good find! 😄 this is because of the use of `setcdr` in the functions `icon-for-file` & `icon-for-mode` which actually updates the `all-the-icons-icon-alist` in situ so that it's modified for all subsequent calls.

**Comment by sebastiencs** [comment]
Thank you
