### ISSUE TITLE
all-the-icons-install-fonts fails with "No such file or directory, /fonts/material-design-icons.ttf"

### ISSUE THREAD

**Issue by joehillen** [domtronn/all-the-icons.el#60]
```
mm-write-region: Opening output file: No such file or directory, /fonts/material-design-icons.ttf
```

* GNU Emacs 25.2.1
* Arch Linux

**Comment by motecshine** [comment]
May be refer to this PR(Google material design)[https://github.com/domtronn/all-the-icons.el/pull/35]

**Comment by domtronn** [comment]
Hey @joehillen, 

Could you run `(getenv "XDG_DATA_HOME")` and describe the following variable `window-system` please? 🙂 I have a feeling this is to do with #57

**Comment by MissingNoIOI** [comment]
I have the same problem with Fedora 25 using Emacs 25 and GNOME 3.22. The problem is that $XDG_DATA_HOME isn't set. When setting it manually to ~/.local/share the installation succeeds

**Comment by joehillen** [comment]
Yeah, setting `XDG_DATA_HOME` fixes it. But the real problem is that there is no guarantee that `XDG_*` variables are set on Linux. Generally the practice is to check for the variable and then default to something if it is not set. 

I've been using Linux for 10+ years and this is the first time ever that I've had to set `XDG_DATA_HOME` for anything.

**Comment by domtronn** [comment]
Cool, well, Emacs only distinguishes between `ns` and `x` window systems _(i.e. MacOS vs Linux)_ so I'm not going to be able to distinguish between different distributions of Linux... 

You can always run the function with a prefix and it will prompt you for the install directory, _i.e._

```el
C-u M-x all-the-icons-install-fonts
```

But I will update the [`x` window system condition](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L684) to default back to `~/.local/share/fonts` if the `XDG_...` environment variable isn't set 🙂
