### ISSUE TITLE
[Question] Is it possible to make the folders in black color, for a light theme ?

### ISSUE THREAD

**Issue by justinjk007** [domtronn/all-the-icons.el#61]
[This is what](http://i.imgur.com/tdcaq1q.png) it looks like now, as you can see it not very different and has a bad contrast.

I am using [solarized-light](http://ethanschoonover.com/solarized)  theme btw.

Thanks

**Comment by domtronn** [comment]
All of the inherited faces _should_ have light and dark variants... See [here](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons-faces.el)

This looks like it's using [`all-the-icons-dired`](https://github.com/jtbm37/all-the-icons-dired)? I can't seem to reproduce this though, I used `solarized-light` and got the following;

<img width="916" alt="screen shot 2017-04-28 at 06 47 56" src="https://cloud.githubusercontent.com/assets/5881414/25515860/0ea6e788-2bdf-11e7-828e-21082f495ba4.png">

**Comment by justinjk007** [comment]
Does the dark font automatically turn on, or do I have to specify something in my manual? 
Thanks

**Comment by domtronn** [comment]
Ah strange... That face changes for me whenever I swap to `solarized-light` and it looks like it's defined to use light and dark colours...

```el
(defface all-the-icons-dired-dir-face
  '((((background dark)) :foreground "white")
    (((background light)) :foreground "black"))
  "Face for the directory icon"
  :group 'all-the-icons-faces)
```

I'm glad you got it fixed though!
