### ISSUE TITLE
Invalid character

### ISSUE THREAD

**Issue by kadern0** [domtronn/all-the-icons.el#63]
Hi,
I'm getting this error:
Debugger entered--Lisp error: (error "Invalid character: 59657, #o164411, #xe909")
  eval-buffer(#<buffer  *load*<3>> nil "~/.emacs.d/modules/all-the-icons/data/data-alltheicons.el" nil t)  ; Reading at buffer position 88  

Not sure if this is related, but the only commands I have available are:
Possible completions are:
all-the-icons-insert 	all-the-icons-insert-alltheicon
all-the-icons-insert-faicon 	all-the-icons-insert-fileicon
all-the-icons-insert-material 	all-the-icons-insert-octicon
all-the-icons-insert-wicon 	all-the-icons-install-fonts

Any idea?

**Comment by domtronn** [comment]
Hey @kadern0, could you please provide a little more information like your OS? Emacs Version? Also, could you try calling `(insert "\xe905")` in a `*scratch*` buffer?

**Comment by kadern0** [comment]
Hi @domtronn , I really appreciate your quick answer. When I run this insert in the buffer it does work (I can see Apache's camel). I'm running OS X El Capitan v 10.11.6 and GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

Cheers.

**Comment by domtronn** [comment]
Thanks for the info!

Hmm, I'm not sure - Those commands look correct, they're the only ones that should be autoloaded and interactive when you get the package. When you call

```el
M-x all-the-icons-insert-alltheicon
```

Do the icons look correct in the minibuffer? I'm using [`ivy`](https://github.com/abo-abo/swiper) and it looks like this for me;
<img width="548" alt="screen shot 2017-05-03 at 12 48 36" src="https://cloud.githubusercontent.com/assets/5881414/25659266/d867f418-2ffe-11e7-856c-6ee96ef6503e.png">

The only other things I can think are, have you properly installed all the fonts _(especially [`all-the-icons`](https://github.com/domtronn/all-the-icons.el/blob/master/fonts/all-the-icons.ttf))_. Also, sometimes MacOS can be a bit funny with font cache invalidation, so simplest thing is to restart the Mac 😅

**Comment by kadern0** [comment]
This command works also for me:
![screen shot 2017-05-03 at 12 53 53](https://cloud.githubusercontent.com/assets/13137996/25659494/f2cf14f2-2fff-11e7-9052-b27fa659c97a.png)

But not any of these from the README:
**The simplest usage for this package is to use the following functions;**

all-the-icons-icon-for-buffer
all-the-icons-icon-for-file
all-the-icons-icon-for-mode

**Comment by domtronn** [comment]
Those functions are _non-interactive_ as oppose to _interactive_, which is kind of the Emacs Lisp equivalent of private/public 🙂 

So, you can only call those from within ELisp code, so you should be able to do

```el
M-: (all-the-icons-icon-for-buffer)
```

Where `M-:` is the binding for `eval-expression`
