### ISSUE TITLE
mm-write-region: Opening output file: No such file or directory, ~/.local/share/fonts/material-design-icons.ttf

### ISSUE THREAD

**Issue by tlegutko** [domtronn/all-the-icons.el#64]
Hi, today I was installing your package and I ran into issue very similar to #60.
`mm-write-region: Opening output file: No such file or directory, /home/tlegutko/.local/share/fonts/material-design-icons.ttf`
But the problem was not the XDG_DATA_HOME (I didn't have it set, but when I set it I still had the same error - so auto-resolution was correct), but it still assumed that I should have material-design-icons.ttf prior to installation - when I downloaded the file manually, the installation went smoothly. So I think one of the following should ease the installation process:
1. Either this file is somehow required and please mention it in README installation step.
2. Check for this file shouldn't fail and it should just download it during installation process.
I'm leaning onto the second, because during installation it downloaded several other fonts, including material design icons..

My setup: Arch Linux, GNU Emacs 25.2.1, all-the-icons 2.5.2.

**Comment by domtronn** [comment]
Hi @tlegutko, are you sure the full path is present? _i.e._ `.local`, `share`, `fonts` all exist? Cause I'm guessing it's trying to write to a folder that doesn't exist.

> 1. Either this file is somehow required and please mention it in README installation step.

This is already documented in the `README` [here](https://github.com/domtronn/all-the-icons.el/#installing-fonts)

> 2. Check for this file shouldn't fail and it should just download it during installation process.

Since the install script doesn't work on _all_ platforms, I don't want to add it as an automated part of installation, users should be very aware of what they're doing since it needs to install things at a system level.

I don't think it's the downloading that's an issue - If it's the directory path not being present, I could add something to check/create these before downloading the fonts 🙂

**Comment by tlegutko** [comment]
> Hi @tlegutko, are you sure the full path is present? i.e. .local, share, fonts all exist? Cause I'm guessing it's trying to write to a folder that doesn't exist.

You're right, I didn't have the `fonts/` directory in my `~/.local/share/`.

> This is already documented in the README here
In order for the icons to work it is very important that you install the Resource Fonts included in this package, they are available in the fonts directory. **You can also install the latest fonts for this package in the (guessed?) based on the OS by calling the following function;**

Emphasis mine, the way I read it, manual installation of fonts in correct directory seems to be _equivalent_ to running the script ("also" suggests alternative way of doing the same), not the _prerequisite_, I think some line with explicit `copy the files from this repo's fonts/ directory to your ~/.local/share/fonts`, would be much more clear.

> I don't think it's the downloading that's an issue - If it's the directory path not being present, I could add something to check/create these before downloading the fonts :slightly_smiling_face:

I think you're right, I created the directory and downloaded just `material-design-fonts.ttf` and other fonts were downloaded by the script, so it might've been just missing directory. If adding check/creating these would fix this problem, then I think that's the easiest solution. I can see why you don't want to create complicated cross-platform installation script, but if you're this one check to absolutely seamless installation process, I think it's definitely worth a try :).

**Comment by domtronn** [comment]
I've pushed a fixed for the installing to create the directory recursively if it doesn't exist.

I'd appreciate it if you could try out the newest version and check it works 🙂 Then I can close this issue!

**Comment by tlegutko** [comment]
Unfortunately, doesn't work.
I recreated first-install-scenario:
1. uninstalled `'all-the-icons`
2. deleted `.local/share/fonts` drectory
3. restarted emacs and installed `all-the-icons 2.6.2`
![image](https://cloud.githubusercontent.com/assets/10455138/25860551/29d32d94-34e2-11e7-8d23-c430ab8fc861.png)
3. `M-x all-the-icons-install-fonts` just gives me back message `all-the-icons-install-fonts: Wrong type argument: stringp, nil`.

Quick edebug session told me the problem is with this line:
```      (unless (file-directory-p font-dest) (mkdir font-dest t))```

`font-dest` is still nill at this point.

**Comment by domtronn** [comment]
Hmm, I didn't think `font-dest` _could_ be `nil`.

That line basically says that if you've not already set `font-dest` _(i.e. by calculating it based on the `window-system`)_ then prompt the user for a directory to install them to.

How are you running the install command? 
Are you running it interactively or as part of some config?

**Comment by tlegutko** [comment]
I'm running `all-the-icons-install-fonts` interactively, I also tried running it with `C-u` prefix to make sure it looks for default path. It's interesting, because version earlier it seemed to have the correct path, it just didn't try to create the directory.

**Comment by domtronn** [comment]
I figured out the issue! And it's fixed by #66...

The problem is that calling

```
(font-dest (unless font-dest (read-directory-name))
```

Sets `font-dest` back to `nil` _because_ `font-dest` is already defined, really it should be an `or` statement to use the already defined value.

**Comment by tlegutko** [comment]
Great! I'll happily report back how new version works once you release it :).

**Comment by tlegutko** [comment]
everything installs without problems (when there is no ~/.local/share/fonts directory beforehand) on version 2.6.4, thanks!
