### ISSUE TITLE
Can't download fonts

### ISSUE THREAD

**Issue by s-kostyaev** [domtronn/all-the-icons.el#65]
When I try to install fonts with `all-the-icons-install-fonts` I see this error on emacs 25.2 on linux:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-directory-p(nil)
  (if (file-directory-p font-dest) nil (mkdir font-dest t))
  (let* ((url-format "https://github.com/domtronn/all-the-icons.el/blob/master/fonts/%s?raw=true") (font-dest (cond ((eql window-system (quote x)) (concat (or (getenv "XDG_DATA_HOME") (concat ... "/.local/share")) "/fonts/")) ((eql window-system (quote mac)) (concat (getenv "HOME") "/Library/Fonts/")) ((eql window-system (quote ns)) (concat (getenv "HOME") "/Library/Fonts/")))) (known-dest\? (stringp font-dest)) (font-dest (if font-dest nil (read-directory-name "Font installation directory: " "~/")))) (if (file-directory-p font-dest) nil (mkdir font-dest t)) (mapc (function (lambda (font) (url-copy-file (format url-format font) (expand-file-name font font-dest) t))) all-the-icons-font-names) (if known-dest\? (progn (message "Fonts downloaded, updating font cache... <fc-cache -f -v> ") (shell-command-to-string (format "fc-cache -f -v")))) (message "%s Successfully %s `all-the-icons' fonts to `%s'!" (all-the-icons-wicon "stars" :v-adjust 0.0) (if known-dest\? "installed" "downloaded") font-dest))
  (progn (let* ((url-format "https://github.com/domtronn/all-the-icons.el/blob/master/fonts/%s?raw=true") (font-dest (cond ((eql window-system (quote x)) (concat (or ... ...) "/fonts/")) ((eql window-system (quote mac)) (concat (getenv "HOME") "/Library/Fonts/")) ((eql window-system (quote ns)) (concat (getenv "HOME") "/Library/Fonts/")))) (known-dest\? (stringp font-dest)) (font-dest (if font-dest nil (read-directory-name "Font installation directory: " "~/")))) (if (file-directory-p font-dest) nil (mkdir font-dest t)) (mapc (function (lambda (font) (url-copy-file (format url-format font) (expand-file-name font font-dest) t))) all-the-icons-font-names) (if known-dest\? (progn (message "Fonts downloaded, updating font cache... <fc-cache -f -v> ") (shell-command-to-string (format "fc-cache -f -v")))) (message "%s Successfully %s `all-the-icons' fonts to `%s'!" (all-the-icons-wicon "stars" :v-adjust 0.0) (if known-dest\? "installed" "downloaded") font-dest)))
  (if (or pfx (yes-or-no-p "This will download and install fonts, are you sure you want to do this?")) (progn (let* ((url-format "https://github.com/domtronn/all-the-icons.el/blob/master/fonts/%s?raw=true") (font-dest (cond ((eql window-system ...) (concat ... "/fonts/")) ((eql window-system ...) (concat ... "/Library/Fonts/")) ((eql window-system ...) (concat ... "/Library/Fonts/")))) (known-dest\? (stringp font-dest)) (font-dest (if font-dest nil (read-directory-name "Font installation directory: " "~/")))) (if (file-directory-p font-dest) nil (mkdir font-dest t)) (mapc (function (lambda (font) (url-copy-file (format url-format font) (expand-file-name font font-dest) t))) all-the-icons-font-names) (if known-dest\? (progn (message "Fonts downloaded, updating font cache... <fc-cache -f -v> ") (shell-command-to-string (format "fc-cache -f -v")))) (message "%s Successfully %s `all-the-icons' fonts to `%s'!" (all-the-icons-wicon "stars" :v-adjust 0.0) (if known-dest\? "installed" "downloaded") font-dest))))
  all-the-icons-install-fonts((4))
  funcall-interactively(all-the-icons-install-fonts (4))
  call-interactively(all-the-icons-install-fonts record nil)
  command-execute(all-the-icons-install-fonts record)
  #[257 "\304\305!\203\f
```

**Comment by domtronn** [comment]
Hey @s-kostyaev, this is part of the ongoing work around #64.

Basically, I made an update to make the fonts directory if it doesn't exist.
However, as your error shows, the font destination folder is somehow `nil`... I'm not sure how since the `font-dest` value show always end up in a result 😅 

I'm hoping to figure this out in the next couple of hours.

**Comment by s-kostyaev** [comment]
@domtronn I can fix it with PR.

**Comment by s-kostyaev** [comment]
The problem was with strange `let*` behaviour.

**Comment by domtronn** [comment]
I'm not sure about that... The help for `let*` states

> `Each VALUEFORM can refer to the symbols already bound by this VARLIST.`

Also, it's documented [here](https://www.gnu.org/software/emacs/manual/html_node/eintr/fwd_002dpara-let.html) that the function [`forward-paragraph`](https://github.com/cpitclaudel/emacs/blob/master/lisp/textmodes/paragraphs.el#L240-L248) uses the same symbol twice during a `let*` binding, 

And when running the following code

```el
(let* ((a 5)
       (b 4)
       (a (+ a b)))
  a)
```

You should get 9, I've tried this on Emacs 25.1 and Emacs 25.2 - I also couldn't find any documentation to state that this had changed/behaves differently between platforms?

**Comment by s-kostyaev** [comment]
When I evaluate this form I see 9. I don't know why, but code in PR was fix issue for me.

**Comment by s-kostyaev** [comment]
Another solution - you can move `read-directory-name` to case `t` in `cl-case`. I can open new PR with this solution 😄

**Comment by domtronn** [comment]
I'm afraid you can't put the `read-directory-name` into the `cl-case` as the `known-dest?` variable is basically to tell you whether or not they were installed to the best directory, in which case it runs `fc-cache -f -v` to clear the font cache which is slow, so I only want to do this if they're installed to the real directories.

That's why I do the `read-directory-name` afterwards if that makes sense? 😅 

I'm going to do a bit more investigation as well, and if I can't figure it out, I'll put your fix in 👍

**Comment by pmilosev** [comment]
@domtronn I'm pretty new to Elisp, but I'm sure it's this line that causes issues
`(font-dest (unless font-dest (read-directory-name "Font installation directory: " "~/")))`

Basically, the _unless_ statement returns _nil_ when the condition is true, and that _nil_ is then assigned to font-dest.
I saw there is already a pull request that fixes the issue.

**Comment by s-kostyaev** [comment]
@pmilosev right. For fix it you may just use `or` instead of `unless`.
