### ISSUE TITLE
Use `rear-nonsticky` text property.

### ISSUE THREAD

**Issue by joostkremers** [domtronn/all-the-icons.el#68]
Currently, when typing e.g.,

    (insert (all-the-icons-faicon "dropbox"))

and then hitting `C-x c-e`, the Dropbox icon is inserted in the buffer, but in such a way that subsequent characters inherit the icon's text properties. Since these include a `face` property, characters inserted immediately after the Dropbox icon are displayed in the same `FontAwesome` font, which is usually not what you'd want. Adding the text property `rear-nonsticky` to the icon with the value `t` solves this issue.

Would it be a good idea to add this text property to the string returned by `all-the-icons-faicon` and similar functions?

**Comment by domtronn** [comment]
Thanks for bringing this to my attention! Didn't know it existed 🙂

**Comment by joostkremers** [comment]
Thanks!
