### ISSUE TITLE
Feature request: all-the-icons-icon-for-url

### ISSUE THREAD

**Issue by Kungsgeten** [domtronn/all-the-icons.el#73]
It would be nice to have a function `all-the-icons-icon-for-url` which chooses an icon based on a URL. Ofcourse it would be hard to cover all possibilities, but as a starter the function and the alist could be added, and then people could send in pull requests with new link types.

For instance if the URL matches `wikipedia.org`, the Wikipedia icon could be used.

**Comment by tzz** [comment]
...maybe it could pull down the favicon, convert it, and store it in cache. No need for manual configuration.
