### ISSUE TITLE
All the icons won't install with a 404

### ISSUE THREAD

**Issue by japanoise** [domtronn/all-the-icons.el#79]
1. Attempt to install all-the-icons (use-package here, same problem with package-install)
```elisp
(use-package all-the-icons
  :ensure t)
```
2. `C-x C-e`

## Expected

Package installed and working

## Actual

Package fails to install because it can't find [this file (404)](http://melpa.org/packages/memoize-20130421.1234.el)

Contents of my \*messages\* after trying a package-install:

```
Contacting host: melpa.org:80
helm-M-x: http://melpa.org/packages/memoize-20130421.1234.el: Not found
```

**Comment by japanoise** [comment]
Should add that memoize has been installed via package-install and seems to be working.

**Comment by domtronn** [comment]
I'm not sure why this would happen? The latest version of [**Memoize**](http://melpa.milkbox.net/#/memoize) is **20170720.1802** - It shouldn't try and install the package from 2013?

I'm assuming you're refreshing your package list before updating?

**Comment by japanoise** [comment]
Having done that, emacs installs all-the-icons succesfully… but segfaults if I try to open neotree with it.

**Comment by domtronn** [comment]
Have you installed all the required fonts?

**Comment by japanoise** [comment]
They're showing up in fc-list, yes.

**Comment by domtronn** [comment]
How were the fonts installed? And what packages do you have that use `all-the-icons`?

I've only ever seen Segfaults happen when people have installed the _incorrect_ versions of the fonts as they have _very strict_ unicode character mappings. If one of the mappings is incorrect, it seems to crash...

I'm not sure of a way to guard against this, but I may start looking into it to safe guard against Segfaults if this is the case.

**Comment by wyuenho** [comment]
Please file a new issue if segfault is still a problem. The version of memoize was probably pulled from Melpa, but it doesn't look like a problem anymore for recent versions.

**Comment by japanoise** [comment]
I suspect it was something to do with my old OS install. It's working now with no issues. Thank you for your time and patience.
