### ISSUE TITLE
Typescript icon is not shows

### ISSUE THREAD

**Issue by rasdaniil** [domtronn/all-the-icons.el#80]
Hi!
All icons seem to work, but TS icon is not there 
I'm using this settings: (setq neo-theme 'icons)

Is there a quick fix for that..? Thanks!

**Comment by domtronn** [comment]
Try the latest version, hopefully should get all the `typescript` icons you could want :)

**Comment by rasdaniil** [comment]
Thanks for response!
I've tries launching all-the-icons-install-fonts but it doesn't seem to show typescript anyway :)

**Comment by cgiroir** [comment]
I've upgraded the package and installed the fonts and I'm seeing Typescript icons now 👍

**Comment by domtronn** [comment]
@rasdaniil You need to upgrade the `all-the-icons` package itself. You can do this by calling

```el
(package-reinstall "all-the-icons")
;; or
M-x package-reinstall all-the-icons
```

Then just restart emacs and it should work, as @cgiroir has found :)

**Comment by rasdaniil** [comment]
I've just notices after reinstalling ubuntu that it works now, thanks!
