### ISSUE TITLE
How to download fonts behind a firewall?

### ISSUE THREAD

**Issue by eflanigan00** [domtronn/all-the-icons.el#84]
I'm behind a firewall and cant fetch from GitHub.
 If I have a clone of the repo can I fetch them from here:
 all-the-icons.el/fonts

Specifically for this command:

     M-x all-the-icons-install-fonts

**Comment by wyuenho** [comment]
The question is, how to whitelist the Github URL on your firewall. I'm afraid there's nothing can be done with this project here.
