### ISSUE TITLE
Fonts broken after upgrade to Emacs 25.3

### ISSUE THREAD

**Issue by justinjk007** [domtronn/all-the-icons.el#85]
All characters are just a  blank box after upgrading to Emacs 25,5, I'm on windows. Al I did was replaced the old binaries and dependencies starlight off from GNU mirror , I'm still using the same config which is working fine on my desktop that has Emacs 25.2 and it works all fine there. 

Thanks for your time

**Comment by justinjk007** [comment]
This is what it looks like by the way..

![output](https://user-images.githubusercontent.com/12916795/31279354-c6f06a7e-aa76-11e7-9a16-9bd617e3331f.PNG)

**Comment by domtronn** [comment]
This seems to be an issues with [`all-the-icons-dired`](https://github.com/jtbm37/all-the-icons-dired), as you can see from the screenshot **below** - The icons for NeoTree are all correct and it's showing icons from multiple Font Families, whereas the `dired-mode` one is showing the wrong icons. This does seem to be an issue with **Emacs 25.3+** but raise it with the library please.

If I find anything useful, I'll add it :)

<img width="1231" alt="screen shot 2017-10-11 at 10 34 47" src="https://user-images.githubusercontent.com/5881414/31432937-d6f309a2-ae6f-11e7-94fa-f448ab340fe1.png">

**Comment by justinjk007** [comment]
OK I start an issue there then, thanks for figuring it out.

**Comment by justinjk007** [comment]
I would also like to point out that my spaceline customization using this snippet also shows an empty box like above.

```clojure
  ;; fancy git icon
  (defadvice vc-mode-line (after strip-backend () activate)
    (propertize (all-the-icons-octicon "git-branch")
		'face `(:family ,(all-the-icons-octicon-family) :height 1.2)
		'display '(raise -0.1))
    (when (stringp vc-mode)
      (let ((gitlogo (replace-regexp-in-string
		      "^ Git"
		      (propertize (all-the-icons-octicon
				   "git-branch"
				   :face 'all-the-icons-orange)
				  'display '(raise 0)
				  ) vc-mode)))
	(setq vc-mode gitlogo))))
```

**Comment by justinjk007** [comment]
I updated emacs to the 64 bit version , bammm no more problemo!!
