### ISSUE TITLE
Octicons, Faicon aren't being displayed

### ISSUE THREAD

**Issue by metrafull2** [domtronn/all-the-icons.el#91]
I don't know why these 2 icons cannot being displayed I leave a picture. I'm using windows 10 with emacs 25.3.1, I have installed the fonts in my computer.
<img width="149" alt="all-the-icons" src="https://user-images.githubusercontent.com/28741504/33752722-70b0a89c-dbb1-11e7-99b3-b62507605ad3.png">

**Comment by wyuenho** [comment]
I've just updated the README. Can you diagnose the problem according to [this troubleshooting guide](https://github.com/domtronn/all-the-icons.el/blob/master/README.md#troubleshooting)? Let me know if you still can't solve the problem.

Also checkout #106

**Comment by dgchurchill** [comment]
I hit a similar problem. I have Consolas set as my default font as per the line below. If I remove this setting from my init.el then the icons render correctly.

`(set-face-font 'default "-*-Consolas-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")`

**Comment by dgchurchill** [comment]
After following the troubleshooting guide I now have the following fix in my `init.el`:

    (set-face-font 'default "-*-Consolas-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")

    (let ((fontset (face-attribute 'default :fontset)))
      (set-fontset-font fontset '(?\xf000 . ?\xf2ff) "FontAwesome" nil 'append)
    )

I can do the same to get the Octicon icon set working, but I can't get them both working at the same time as it seems that the codepoints used in these two sets overlap.

**Comment by dgchurchill** [comment]
So I've found a fix and it's as simple as changing the registry of my default font from `iso10646` to `iso8859`. I don't really understand what this parameter does but it seems to work. Seems to be Windows specfic as on macOS I have the font set with the `iso10646` registry without any problems.

In summary, changing the face config in my init.el from:

    (set-face-font 'default "-*-Consolas-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")

to:

    (set-face-font 'default "-*-Consolas-normal-normal-normal-*-14-*-*-*-m-0-iso8859-1")

fixed this issue for me.

It also works fine with the simpler form `(set-face-font 'default "Consolas-11")`

**Comment by wyuenho** [comment]
> changing the registry of my default font from iso10646 to iso8859. I don't really understand what this parameter does but it seems to work. Seems to be Windows specfic as on macOS I have the font set with the iso10646 registry without any problems.

Sounds like a bug you should report upstream. `M-x report-emacs-bug` is your friend.

**Comment by jfmcbrayer** [comment]
It is fair to say this is an upstream bug, but it probably affects all Windows users, so it might be worth mentioning in the README.
