### ISSUE TITLE
many icons from fonts are not displayed correctly

### ISSUE THREAD

**Issue by stardiviner** [domtronn/all-the-icons.el#93]
![all-the-icons org-clock icon error](https://user-images.githubusercontent.com/378699/34189299-c70031d6-e575-11e7-8eec-f17f163fe597.png)

Here is my original code:

    (defun *org-clock ()
      "Show org-clock info."
      (when (and (active)
                 (org-clock-is-active)
                 org-clock-idle-timer)
        ;; get [0:05] from `org-clock-get-clock-string'
        (propertize
         (concat
          (all-the-icons-material "timer")
          (propertize " " 'face 'variable-pitch)
          (format "%s"
                  (org-minutes-to-clocksum-string (org-clock-get-clocked-time)))
          (propertize " " 'face 'variable-pitch))
         'face 'mode-line-data-face))
      )

And I tried to insert icon directly with:

`[M-x all-the-icons-insert RET timer]`



It works fine, and ivy display it correctly.

Also I runned command "$ `fc-cache -f`"

When I check out variable `all-the-icons/material-icons-alist`, I found many icons
display error, same to other all-the-icons fonts.

I also tried to run command `[M-x all-the-icons-install-fonts]`. not work too.

**Comment by wyuenho** [comment]
I've just updated the README. Can you diagnose the problem according to [this troubleshooting guide](https://github.com/domtronn/all-the-icons.el/blob/master/README.md#troubleshooting)? Let me know if you still can't solve the problem.

**Comment by wyuenho** [comment]
Also, checkout #106

**Comment by stardiviner** [comment]
Seems fixed by #106. Thanks.
